In [23]:
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.linear_model import LinearRegression
import os
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import LSTM
import datetime
from numpy import hstack
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

In [2]:
import tensorflow

Testing different types of LSTM models to input teams data into and obtain prediction

In [3]:
#obtain list of dates
directory = "Oklahoma City Thunder"
list_dates = []
for filename in os.listdir(directory):
    if filename.endswith(".csv"):
        list_dates.append(filename)

In [4]:
# create dictionary 
final_data = {}

In [5]:
opponents = {}
# reads in each csv
for i in list_dates:
    data = pd.read_csv(f"{directory}/{i}", index_col=0)
    #gathers data and adds to dict
    date = data["Date"].tolist()[0]
    
    # (error for now) opponents[date] = data["Opponent"][0]
    
    data[date] = data["Score"]
    final_data[date] = data[date]
    final_data[date].append

In [6]:
# convert dict to dataframe
data_df = pd.DataFrame(final_data)
data_df

11/09/2022  10/29/2022  10/19/2022  10/25/2022  \
Aaron Wiggins                  6.25       17.25         NaN       31.00   
Aleksej Pokusevski            41.50       16.50       26.25       16.00   
Darius Bazley                  2.75       26.50       21.50       18.50   
Eugene Omoruyi                  NaN        4.00        8.50         NaN   
Isaiah Joe                     9.50       20.50        0.00        0.00   
Jalen Williams                22.75       29.75        6.00         NaN   
Jaylin Williams                 NaN         NaN         NaN         NaN   
Jeremiah Robinson-Earl         5.75        0.00       15.25       21.25   
Josh Giddey                   45.25         NaN       36.75         NaN   
Kenrich Williams               4.25       12.00       14.50       23.75   
Lindy Waters III                NaN         NaN         NaN         NaN   
Luguentz Dort                 34.25       30.50       22.50        6.50   
Mike Muscala                  14.50        3.50        6.75       25.50   
Ousmane Dieng                   NaN         NaN        1.25        4.75   
Shai Gilgeous-Alexander       53.00       63.50       57.00       63.25   
Tre Mann                      35.50       14.25       20.50       40.50   

                         10/27/2022  10/22/2022  10/23/2022  11/13/2022  \
Aaron Wiggins                 26.00       14.50       11.00       12.25   
Aleksej Pokusevski            28.50        7.25        4.00       23.00   
Darius Bazley                 27.75       23.50        0.00         NaN   
Eugene Omoruyi                  NaN        2.00       18.75         NaN   
Isaiah Joe                     0.00         NaN        9.75       16.75   
Jalen Williams                  NaN         NaN         NaN        7.00   
Jaylin Williams                 NaN         NaN       14.50         NaN   
Jeremiah Robinson-Earl        11.00       14.50       25.50       26.75   
Josh Giddey                     NaN       47.50       18.00       54.00   
Kenrich Williams              22.75       11.25       11.50       15.25   
Lindy Waters III                NaN        1.25        4.75         NaN   
Luguentz Dort                 34.75       33.25       30.75       30.25   
Mike Muscala                   7.75       29.00       24.75       14.00   
Ousmane Dieng                  3.50        0.00       23.00         NaN   
Shai Gilgeous-Alexander       44.75       42.25         NaN       63.25   
Tre Mann                      27.75       24.50       19.25        3.50   

                         11/07/2022  11/11/2022  11/05/2022  11/01/2022  \
Aaron Wiggins                   NaN       37.75       -1.50        6.25   
Aleksej Pokusevski              NaN       27.25         NaN       38.75   
Darius Bazley                 28.00         NaN       24.25       15.50   
Eugene Omoruyi                  NaN       30.75        0.00         NaN   
Isaiah Joe                      NaN        2.00       10.25        0.00   
Jalen Williams                15.00       31.25       13.25       10.25   
Jaylin Williams                 NaN         NaN        5.25         NaN   
Jeremiah Robinson-Earl        14.50         NaN       19.75       28.25   
Josh Giddey                   20.00       34.75       24.50       26.25   
Kenrich Williams              29.50       13.50       10.25         NaN   
Lindy Waters III                NaN         NaN         NaN         NaN   
Luguentz Dort                 21.75       26.25       19.50       22.50   
Mike Muscala                  19.50         NaN       15.25         NaN   
Ousmane Dieng                  6.25         NaN       21.50       16.50   
Shai Gilgeous-Alexander       58.75       36.75       26.75       55.50   
Tre Mann                      21.75       23.25        2.00       24.75   

                         11/03/2022  
Aaron Wiggins                   NaN  
Aleksej Pokusevski            22.25  
Darius Bazley                 14.75  
Eugene Omoruyi                  NaN  
Isaiah 

In [7]:
# opp = pd.DataFrame.transpose(pd.DataFrame.from_dict(opponents, orient="index"))
# data_df = data_df.append(opp)

In [8]:

data_df

11/09/2022  10/29/2022  10/19/2022  10/25/2022  \
Aaron Wiggins                  6.25       17.25         NaN       31.00   
Aleksej Pokusevski            41.50       16.50       26.25       16.00   
Darius Bazley                  2.75       26.50       21.50       18.50   
Eugene Omoruyi                  NaN        4.00        8.50         NaN   
Isaiah Joe                     9.50       20.50        0.00        0.00   
Jalen Williams                22.75       29.75        6.00         NaN   
Jaylin Williams                 NaN         NaN         NaN         NaN   
Jeremiah Robinson-Earl         5.75        0.00       15.25       21.25   
Josh Giddey                   45.25         NaN       36.75         NaN   
Kenrich Williams               4.25       12.00       14.50       23.75   
Lindy Waters III                NaN         NaN         NaN         NaN   
Luguentz Dort                 34.25       30.50       22.50        6.50   
Mike Muscala                  14.50        3.50        6.75       25.50   
Ousmane Dieng                   NaN         NaN        1.25        4.75   
Shai Gilgeous-Alexander       53.00       63.50       57.00       63.25   
Tre Mann                      35.50       14.25       20.50       40.50   

                         10/27/2022  10/22/2022  10/23/2022  11/13/2022  \
Aaron Wiggins                 26.00       14.50       11.00       12.25   
Aleksej Pokusevski            28.50        7.25        4.00       23.00   
Darius Bazley                 27.75       23.50        0.00         NaN   
Eugene Omoruyi                  NaN        2.00       18.75         NaN   
Isaiah Joe                     0.00         NaN        9.75       16.75   
Jalen Williams                  NaN         NaN         NaN        7.00   
Jaylin Williams                 NaN         NaN       14.50         NaN   
Jeremiah Robinson-Earl        11.00       14.50       25.50       26.75   
Josh Giddey                     NaN       47.50       18.00       54.00   
Kenrich Williams              22.75       11.25       11.50       15.25   
Lindy Waters III                NaN        1.25        4.75         NaN   
Luguentz Dort                 34.75       33.25       30.75       30.25   
Mike Muscala                   7.75       29.00       24.75       14.00   
Ousmane Dieng                  3.50        0.00       23.00         NaN   
Shai Gilgeous-Alexander       44.75       42.25         NaN       63.25   
Tre Mann                      27.75       24.50       19.25        3.50   

                         11/07/2022  11/11/2022  11/05/2022  11/01/2022  \
Aaron Wiggins                   NaN       37.75       -1.50        6.25   
Aleksej Pokusevski              NaN       27.25         NaN       38.75   
Darius Bazley                 28.00         NaN       24.25       15.50   
Eugene Omoruyi                  NaN       30.75        0.00         NaN   
Isaiah Joe                      NaN        2.00       10.25        0.00   
Jalen Williams                15.00       31.25       13.25       10.25   
Jaylin Williams                 NaN         NaN        5.25         NaN   
Jeremiah Robinson-Earl        14.50         NaN       19.75       28.25   
Josh Giddey                   20.00       34.75       24.50       26.25   
Kenrich Williams              29.50       13.50       10.25         NaN   
Lindy Waters III                NaN         NaN         NaN         NaN   
Luguentz Dort                 21.75       26.25       19.50       22.50   
Mike Muscala                  19.50         NaN       15.25         NaN   
Ousmane Dieng                  6.25         NaN       21.50       16.50   
Shai Gilgeous-Alexander       58.75       36.75       26.75       55.50   
Tre Mann                      21.75       23.25        2.00       24.75   

                         11/03/2022  
Aaron Wiggins                   NaN  
Aleksej Pokusevski            22.25  
Darius Bazley                 14.75  
Eugene Omoruyi                  NaN  
Isaiah 

In [9]:
#create dict
final_result = {}

In [10]:

tester = pd.DataFrame.transpose(data_df)

tester["Datetime"] = pd.to_datetime(data_df.columns.tolist()).tolist()

tester

Aaron Wiggins  Aleksej Pokusevski  Darius Bazley  Eugene Omoruyi  \
11/09/2022           6.25               41.50           2.75             NaN   
10/29/2022          17.25               16.50          26.50            4.00   
10/19/2022            NaN               26.25          21.50            8.50   
10/25/2022          31.00               16.00          18.50             NaN   
10/27/2022          26.00               28.50          27.75             NaN   
10/22/2022          14.50                7.25          23.50            2.00   
10/23/2022          11.00                4.00           0.00           18.75   
11/13/2022          12.25               23.00            NaN             NaN   
11/07/2022            NaN                 NaN          28.00             NaN   
11/11/2022          37.75               27.25            NaN           30.75   
11/05/2022          -1.50                 NaN          24.25            0.00   
11/01/2022           6.25               38.75          15.50             NaN   
11/03/2022            NaN               22.25          14.75             NaN   

            Isaiah Joe  Jalen Williams  Jaylin Williams  \
11/09/2022        9.50           22.75              NaN   
10/29/2022       20.50           29.75              NaN   
10/19/2022        0.00            6.00              NaN   
10/25/2022        0.00             NaN              NaN   
10/27/2022        0.00             NaN              NaN   
10/22/2022         NaN             NaN              NaN   
10/23/2022        9.75             NaN            14.50   
11/13/2022       16.75            7.00              NaN   
11/07/2022         NaN           15.00              NaN   
11/11/2022        2.00           31.25              NaN   
11/05/2022       10.25           13.25             5.25   
11/01/2022        0.00           10.25              NaN   
11/03/2022         NaN           11.00              NaN   

            Jeremiah Robinson-Earl  Josh Giddey  Kenrich Williams  \
11/09/2022                    5.75        45.25              4.25   
10/29/2022                    0.00          NaN             12.00   
10/19/2022                   15.25        36.75             14.50   
10/25/2022                   21.25          NaN             23.75   
10/27/2022                   11.00          NaN             22.75   
10/22/2022                   14.50        47.50             11.25   
10/23/2022                   25.50        18.00             11.50   
11/13/2022                   26.75        54.00             15.25   
11/07/2022                   14.50        20.00             29.50   
11/11/2022                     NaN        34.75             13.50   
11/05/2022                   19.75        24.50             10.25   
11/01/2022                   28.25        26.25               NaN   
11/03/2022                   25.25        25.75             16.50   

            Lindy Waters III  Luguentz Dort  Mike Muscala  Ousmane Dieng  \
11/09/2022               NaN          34.25         14.50            NaN   
10/29/2022               NaN          30.50          3.50            NaN   
10/19/2022               NaN          22.50          6.75           1.25   
10/25/2022               NaN           6.50         25.50           4.75   
10/27/2022               NaN          34.75          7.75           3.50   
10/22/2022              1.25          33.25         29.00           0.00   
10/23/2022              4.75          30.75         24.75          23.00   
11/13/2022               NaN          30.25         14.00            NaN   
11/07/2022               NaN          21.75         19.50           6.25   
11/11/2022               NaN          26.25           NaN            NaN   
11/05/2022               NaN          19.50         15.25          21.50   
11/01/2022               NaN          22.50           NaN          16.50   
11/03/2022               NaN          28.75          2.50           7.75   

            Shai Gilgeous-Alexan

In [11]:
tester = tester.sort_values(by="Datetime")

columns = tester.columns.tolist()[:-1]

columns

['Aaron Wiggins',
 'Aleksej Pokusevski',
 'Darius Bazley',
 'Eugene Omoruyi',
 'Isaiah Joe',
 'Jalen Williams',
 'Jaylin Williams',
 'Jeremiah Robinson-Earl',
 'Josh Giddey',
 'Kenrich Williams',
 'Lindy Waters III',
 'Luguentz Dort',
 'Mike Muscala',
 'Ousmane Dieng',
 'Shai Gilgeous-Alexander',
 'Tre Mann']

In [24]:
add = {}

# Perform LSTM analysis

#iterate through index
for column in columns:
    print(column)
    
    add[column] = {}
    
# univariate data prep LSTM
    from numpy import array

    # split sequence
    def split_sequence(sequence, n_steps):
        X, y = list(), list()
        for i in range(len(sequence)):
            # find end of pattern 
            end_ix = i + n_steps
            #check if beyond sequence to break
            if end_ix > len(sequence)-1:
                break
            #gather input and output parts of the pattern
            seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
            X.append(seq_x)
            y.append(seq_y)
        return array(X), array(y)
    # sequence 
    rent_rate = list(tester[column].dropna())
    # number of steps
    n_steps = 3
    if len(rent_rate) < 4:
        continue
    X, y = split_sequence(rent_rate, n_steps)
    # summarize the data
    for i in range(len(X)):
        print(X[i], y[i])

    # reshape from [samples, timesteps] into [samples, timesteps, features]
    n_features = 1
    X = X.reshape((X.shape[0], X.shape[1], n_features))

    model = Sequential()
    model.add(LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
    model.add(Dense(1))
    model.compile(optimizer='adam', loss='mse')

    # fit model
    model.fit(X, y, epochs=200, verbose=0)

    # demonstrate prediction
    x_input = array(rent_rate[-3:])
    x_input = x_input.reshape((1, n_steps, n_features))
    yhat = model.predict(x_input, verbose=0)
    add[column]['Predict'] = yhat.tolist()[0][0]
    
    add[column]['RMSE'] = np.sqrt(mean_squared_error(y[-1], yhat))
    
    add[column]['R2'] = r2_score(y[-1], yhat)
    

Anthony Davis
[37.25 47.75 43.  ] 57.0
[47.75 43.   57.  ] 54.5
[43.  57.  54.5] 39.0
[57.  54.5 39. ] 23.25
[54.5  39.   23.25] 40.5
[39.   23.25 40.5 ] 41.5
[23.25 40.5  41.5 ] 39.0
[40.5 41.5 39. ] 55.0
[41.5 39.  55. ] 55.5


2023-08-29 10:35:05.159695: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2023-08-29 10:35:10.999948: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


TypeError: Singleton array 55.5 cannot be considered a valid collection.

In [39]:
r2_score(y, yhat)

ValueError: Found input variables with inconsistent numbers of samples: [9, 1]

In [32]:
yhat.tolist()[0][0]

48.47819519042969

In [37]:
mean_squared_error([y[-1]], yhat)

TypeError: Expected sequence or array-like, got <class 'float'>

In [125]:
# convert dict to dataframe
Data = pd.DataFrame.from_dict(add, orient='index')

In [126]:
#Predicted outcome for next game

Data

0
Andrew Wiggins    34.251427
Draymond Green    45.562759
JaMychal Green     3.060918
James Wiseman     21.661009
Jonathan Kuminga   8.004239
Jordan Poole      27.125572
Kevon Looney      14.756599
Klay Thompson      4.837108
Moses Moody       33.259537
Stephen Curry     38.617908

In [127]:
# convert dataframe to csv
mypath = "Final_Score/LSTM"
if not os.path.isdir(mypath):
    os.makedirs(mypath)
Data.to_csv(f"{mypath}/{directory}.csv", index=True)

Function below used for multiple teams

In [13]:
#obtain list of dates
directorys = ["Los Angeles Lakers"]


for directory in directorys:
    list_dates = []
    for filename in os.listdir(directory):
        if filename.endswith(".csv"):
            list_dates.append(filename)
    # create dictionary 
    final_data = {}
    
    # reads in each csv
    for i in list_dates:
        data = pd.read_csv(f"{directory}/{i}", index_col=0)

        #gathers data and adds to dict
        date = data["Date"].tolist()[0]
        data[date] = data["Score"]
        final_data[date] = data[date]
    # convert dict to dataframe
    data_df = pd.DataFrame(final_data)
    
    
    tester = pd.DataFrame.transpose(data_df)
    columns = tester.columns.tolist()
    
    #create dict
    final_result = {}
    
    add = {}

    #iterate through index
    for column in columns:
        print(column)

    # univariate data prep LSTM
        from numpy import array

        # split sequence
        def split_sequence(sequence, n_steps):
            X, y = list(), list()
            for i in range(len(sequence)):
                # find end of pattern 
                end_ix = i + n_steps
                #check if beyond sequence to break
                if end_ix > len(sequence)-1:
                    break
                #gather input and output parts of the pattern
                seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
                X.append(seq_x)
                y.append(seq_y)
            return array(X), array(y)
        # sequence 
        rent_rate = list(tester[column].dropna())
        # number of steps
        n_steps = 3
        if len(rent_rate) < 4:
            continue
        X, y = split_sequence(rent_rate, n_steps)
        # summarize the data
        for i in range(len(X)):
            print(X[i], y[i])

        # reshape from [samples, timesteps] into [samples, timesteps, features]
        n_features = 1
        X = X.reshape((X.shape[0], X.shape[1], n_features))

        model = Sequential()
        model.add(LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
        model.add(Dense(1))
        model.compile(optimizer='adam', loss='mse')

        # fit model
        model.fit(X, y, epochs=200, verbose=0)

        # demonstrate prediction
        x_input = array(rent_rate[-3:])
        x_input = x_input.reshape((1, n_steps, n_features))
        yhat = model.predict(x_input, verbose=0)
        add[column] = yhat.tolist()[0][0]
    # convert dict to dataframe
    Data = pd.DataFrame.from_dict(add, orient='index')

    
    # convert dataframe to csv
    mypath = f"Final_Score/LSTM/{directory}"
    if not os.path.isdir(mypath):
        os.makedirs(mypath)
    Data.to_csv(f"{mypath}/{directory}.csv", index=True)

Anthony Davis
[37.25 47.75 43.  ] 57.0
[47.75 43.   57.  ] 54.5
[43.  57.  54.5] 39.0
[57.  54.5 39. ] 23.25
[54.5  39.   23.25] 40.5
[39.   23.25 40.5 ] 41.5
[23.25 40.5  41.5 ] 39.0
[40.5 41.5 39. ] 55.0
[41.5 39.  55. ] 55.5


2023-08-29 10:29:30.294223: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Austin Reaves
[20.75 25.25 23.  ] 4.5
[25.25 23.    4.5 ] 12.5
[23.   4.5 12.5] 10.5
[ 4.5 12.5 10.5] 12.0
[12.5 10.5 12. ] 7.75
[10.5  12.    7.75] 17.5
[12.    7.75 17.5 ] 7.0
[ 7.75 17.5   7.  ] 18.0
[17.5  7.  18. ] 27.25
[ 7.   18.   27.25] 13.5


2023-08-29 10:29:38.637177: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2023-08-29 10:29:39.641492: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Cole Swider
Damian Jones
[ 0. 15.  2.] 11.0
[15.  2. 11.] 6.5
[ 2.  11.   6.5] 6.25
[11.    6.5   6.25] 19.75
[ 6.5   6.25 19.75] 0.0
[ 6.25 19.75  0.  ] 8.5


2023-08-29 10:29:47.657076: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2023-08-29 10:29:48.363140: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Juan Toscano-Anderson
[1.25 4.   5.75] 8.5
[4.   5.75 8.5 ] 19.5
[ 5.75  8.5  19.5 ] 6.5
[ 8.5 19.5  6.5] 4.25
[19.5   6.5   4.25] 5.25
[6.5  4.25 5.25] 10.25


2023-08-29 10:29:56.487506: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2023-08-29 10:29:57.464435: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Kendrick Nunn
[ 4.  11.5  3.5] 21.75
[11.5   3.5  21.75] 14.5
[ 3.5  21.75 14.5 ] 0.5
[21.75 14.5   0.5 ] 7.0
[14.5  0.5  7. ] 1.25
[0.5  7.   1.25] 20.25
[ 7.    1.25 20.25] 8.25
[ 1.25 20.25  8.25] 0.0


2023-08-29 10:30:05.310366: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2023-08-29 10:30:06.032261: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


LeBron James
[52.   51.25 47.  ] 60.75
[51.25 47.   60.75] 40.25
[47.   60.75 40.25] 60.0
[60.75 40.25 60.  ] 47.5
[40.25 60.   47.5 ] 41.75
[60.   47.5  41.75] 42.0
[47.5  41.75 42.  ] 47.5


2023-08-29 10:30:14.105585: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2023-08-29 10:30:14.840768: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Lonnie Walker IV
[15.25 34.75 19.25] 25.0
[34.75 19.25 25.  ] 25.0
[19.25 25.   25.  ] 38.75
[25.   25.   38.75] 12.0
[25.   38.75 12.  ] 8.75
[38.75 12.    8.75] 26.75
[12.    8.75 26.75] 25.75
[ 8.75 26.75 25.75] 38.75


2023-08-29 10:30:22.176722: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2023-08-29 10:30:23.247892: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Matt Ryan
[0.   7.   6.25] 8.25
[7.   6.25 8.25] 6.75
[6.25 8.25 6.75] 1.25
[8.25 6.75 1.25] 3.25
[6.75 1.25 3.25] 16.0
[ 1.25  3.25 16.  ] 8.5
[ 3.25 16.    8.5 ] 16.0


2023-08-29 10:30:30.456841: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2023-08-29 10:30:31.155490: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Max Christie
[9.25 4.75 4.75] 7.5
[4.75 4.75 7.5 ] 16.75
[ 4.75  7.5  16.75] 2.0
[ 7.5  16.75  2.  ] 0.0
[16.75  2.    0.  ] 16.5


2023-08-29 10:30:38.468356: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2023-08-29 10:30:39.167725: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Patrick Beverley
[18.   19.   14.75] 20.5
[19.   14.75 20.5 ] 17.5
[14.75 20.5  17.5 ] 21.0
[20.5 17.5 21. ] 16.5
[17.5 21.  16.5] 10.0
[21.  16.5 10. ] 13.25
[16.5  10.   13.25] 17.75
[10.   13.25 17.75] 10.5


2023-08-29 10:30:46.770604: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2023-08-29 10:30:47.674198: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Russell Westbrook
[34.5 34.5 39.5] 37.75
[34.5  39.5  37.75] 26.5
[39.5  37.75 26.5 ] 21.25
[37.75 26.5  21.25] 20.0
[26.5  21.25 20.  ] 37.25
[21.25 20.   37.25] 41.75
[20.   37.25 41.75] 42.25
[37.25 41.75 42.25] 42.0
[41.75 42.25 42.  ] 34.75


2023-08-29 10:30:57.496297: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2023-08-29 10:30:58.236029: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Scotty Pippen Jr.
Troy Brown Jr.
[21.5 22.  17.5] 19.75
[22.   17.5  19.75] 12.5
[17.5  19.75 12.5 ] 3.25
[19.75 12.5   3.25] 18.5
[12.5   3.25 18.5 ] 20.0
[ 3.25 18.5  20.  ] 16.5
[18.5 20.  16.5] 9.75
[20.   16.5   9.75] 29.5


2023-08-29 10:31:05.743877: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2023-08-29 10:31:06.471548: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Wenyen Gabriel
[10.75 26.5   6.5 ] 2.75
[26.5   6.5   2.75] 0.0
[6.5  2.75 0.  ] 7.5
[2.75 0.   7.5 ] 17.0
[ 0.   7.5 17. ] 10.5
[ 7.5 17.  10.5] 11.5
[17.  10.5 11.5] 15.5
[10.5 11.5 15.5] 13.5


2023-08-29 10:31:14.114575: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2023-08-29 10:31:15.137091: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2023-08-29 10:31:22.839765: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


In [15]:
add

{'Anthony Davis': 48.51462936401367,
 'Austin Reaves': 8.175692558288574,
 'Damian Jones': 9.960127830505371,
 'Juan Toscano-Anderson': 12.818927764892578,
 'Kendrick Nunn': 1.7783564329147339,
 'LeBron James': 40.01310729980469,
 'Lonnie Walker IV': 8.650062561035156,
 'Matt Ryan': 30.1746883392334,
 'Max Christie': 4.937704086303711,
 'Patrick Beverley': 13.961899757385254,
 'Russell Westbrook': 25.376121520996094,
 'Troy Brown Jr.': 19.0633602142334,
 'Wenyen Gabriel': 12.060958862304688}

Backtesting

In [12]:
list_dates

['06-16.csv',
 '06-02.csv',
 '06-10.csv',
 '06-05.csv',
 '06-13.csv',
 '04-17.csv',
 '05-25.csv',
 '05-19.csv',
 '05-27.csv',
 '05-23.csv',
 '05-21.csv',
 '05-09.csv',
 '05-11.csv',
 '05-07.csv',
 '05-13.csv',
 '05-17.csv',
 '05-03.csv',
 '05-29.csv',
 '05-15.csv',
 '05-01.csv',
 '06-08.csv',
 '04-25.csv',
 '04-20.csv',
 '04-23.csv']

In [13]:
collect = []
for name in opponents:
    if opponents[name] not in collect:
        collect.append(opponents[name])

In [14]:
collect

['Golden State Warriors', 'Brooklyn Nets', 'Miami Heat', 'Milwaukee Bucks']

In [14]:
data_df

11/09/2022  10/28/2022  10/30/2022  10/18/2022  \
Anthony Davis               37.25         NaN       47.75       43.00   
Austin Reaves               20.75       25.25       23.00        4.50   
Cole Swider                   NaN         NaN         NaN        2.75   
Damian Jones                 0.00       15.00        2.00         NaN   
Juan Toscano-Anderson        1.25         NaN         NaN        4.00   
Kendrick Nunn                4.00       11.50        3.50       21.75   
LeBron James                52.00       51.25       47.00       60.75   
Lonnie Walker IV              NaN       15.25       34.75       19.25   
Matt Ryan                    0.00         NaN        7.00        6.25   
Max Christie                 9.25         NaN         NaN        4.75   
Patrick Beverley            18.00       19.00       14.75       20.50   
Russell Westbrook           34.50       34.50       39.50       37.75   
Scotty Pippen Jr.             NaN         NaN         NaN        2.00   
Troy Brown Jr.              21.50       22.00       17.50         NaN   
Wenyen Gabriel              10.75       26.50        6.50        2.75   

                       10/26/2022  10/23/2022  10/20/2022  11/13/2022  \
Anthony Davis               57.00        54.5       39.00       23.25   
Austin Reaves               12.50        10.5       12.00        7.75   
Cole Swider                   NaN         NaN         NaN         NaN   
Damian Jones                11.00         6.5        6.25         NaN   
Juan Toscano-Anderson        5.75         8.5       19.50         NaN   
Kendrick Nunn               14.50         0.5        7.00        1.25   
LeBron James                40.25        60.0       47.50         NaN   
Lonnie Walker IV            25.00        25.0       38.75       12.00   
Matt Ryan                    8.25         NaN        6.75        1.25   
Max Christie                 4.75         NaN         NaN        7.50   
Patrick Beverley            17.50        21.0       16.50       10.00   
Russell Westbrook             NaN        26.5       21.25       20.00   
Scotty Pippen Jr.             NaN         NaN         NaN         NaN   
Troy Brown Jr.              19.75        12.5         NaN        3.25   
Wenyen Gabriel               0.00         NaN         NaN        7.50   

                       11/07/2022  11/06/2022  11/04/2022  11/11/2022  \
Anthony Davis               40.50       41.50       39.00       55.00   
Austin Reaves               17.50        7.00       18.00       27.25   
Cole Swider                   NaN         NaN         NaN         NaN   
Damian Jones                19.75         NaN        0.00        8.50   
Juan Toscano-Anderson        6.50        4.25        5.25       10.25   
Kendrick Nunn               20.25        8.25        0.00         NaN   
LeBron James                  NaN       41.75       42.00         NaN   
Lonnie Walker IV              NaN        8.75       26.75       25.75   
Matt Ryan                    3.25       16.00        8.50         NaN   
Max Christie                16.75        2.00        0.00       16.50   
Patrick Beverley              NaN         NaN       13.25       17.75   
Russell Westbrook           37.25       41.75       42.25       42.00   
Scotty Pippen Jr.            3.00         NaN         NaN         NaN   
Troy Brown Jr.              18.50       20.00       16.50        9.75   
Wenyen Gabriel              17.00       10.50       11.50       15.50   

                       11/02/2022  
Anthony Davis               55.50  
Austin Reaves               13.50  
Cole Swider                   NaN  
Damian Jones                  NaN  
Juan Toscano-Anderson         NaN  
Kendrick Nunn                 NaN  
LeBron James                47.50  
Lonnie Walker IV            38.75  
Matt Ryan                   16.00  
Max Christie                  NaN  
Patrick Beverley            10.50  
Russell Westbrook           34.75  
Scotty Pippen Jr.             NaN  
Troy Brown J

In [16]:
directorys

NameError: name 'directorys' is not defined

In [28]:
#obtain list of dates
directorys = collect


for directory in directorys:
    print(directory)
    list_dates = []
    for filename in os.listdir(directory):
        if filename.endswith(".csv"):
            list_dates.append(filename)
    # create dictionary 
    final_data = {}
    
    # reads in each csv
    for i in list_dates:
        data = pd.read_csv(f"{directory}/{i}", index_col=0)

        #gathers data and adds to dict
        date = data["Date"].tolist()[0]
        data[date] = data["Score"]
        final_data[date] = data[date]
    # convert dict to dataframe
    opp = pd.DataFrame(final_data)
    
    
    opp_df = pd.DataFrame.transpose(opp)
    
    opp_df["Datetime"] = pd.to_datetime(opp.columns.tolist()).tolist()
    
    columns = opp_df.columns.tolist()[:-1]
    
    main_test = tester.columns.tolist()[:-2]
    
    for date in tester.loc[tester[0] == directory]["Datetime"]:
        print(date)
        main = tester.loc[tester["Datetime"] < date]
        results = opp_df.loc[opp_df["Datetime"] < date]
    
    
        #create dict
        final_result = {}

        add = {}

        #iterate through index
        for column in columns:
            print(column)

        # univariate data prep LSTM
            from numpy import array

            # split sequence
            def split_sequence(sequence, n_steps):
                X, y = list(), list()
                for i in range(len(sequence)):
                    # find end of pattern 
                    end_ix = i + n_steps
                    #check if beyond sequence to break
                    if end_ix > len(sequence)-1:
                        break
                    #gather input and output parts of the pattern
                    seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
                    X.append(seq_x)
                    y.append(seq_y)
                return array(X), array(y)
            # sequence 
            rent_rate = list(results[column].dropna())
            # number of steps
            n_steps = 5
            if len(rent_rate) < 5:
                continue
            X, y = split_sequence(rent_rate, n_steps)
            # summarize the data
            for i in range(len(X)):
                print(X[i], y[i])

            # reshape from [samples, timesteps] into [samples, timesteps, features]
            n_features = 1
            X = X.reshape((X.shape[0], X.shape[1], n_features))

            model = Sequential()
            model.add(LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
            model.add(Dense(1))
            model.compile(optimizer='adam', loss='mse')

            # fit model
            model.fit(X, y, epochs=200, verbose=0)

            # demonstrate prediction
            x_input = array(rent_rate[-5:])
            x_input = x_input.reshape((1, n_steps, n_features))
            yhat = model.predict(x_input, verbose=0)
            add[column] = yhat.tolist()[0][0]
        # convert dict to dataframe
        Data = pd.DataFrame.from_dict(add, orient='index')


        # convert dataframe to csv
        mypath = f"Final_Score/LSTM/Backtesting/{directory}"
        if not os.path.isdir(mypath):
            os.makedirs(mypath)
        Data.to_csv(f"{mypath}/{directory}_{date}.csv", index=True)
        
        #create dict
        final_result = {}

        add = {}

        
        #iterate through index
        for column in main_test:
            print(column)

        # univariate data prep LSTM
            from numpy import array

            # split sequence
            def split_sequence(sequence, n_steps):
                X, y = list(), list()
                for i in range(len(sequence)):
                    # find end of pattern 
                    end_ix = i + n_steps
                    #check if beyond sequence to break
                    if end_ix > len(sequence)-1:
                        break
                    #gather input and output parts of the pattern
                    seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
                    X.append(seq_x)
                    y.append(seq_y)
                return array(X), array(y)
            # sequence 
            rent_rate = list(main[column].dropna())
            # number of steps
            n_steps = 5
            if len(rent_rate) < 5:
                continue
            X, y = split_sequence(rent_rate, n_steps)
            # summarize the data
            for i in range(len(X)):
                print(X[i], y[i])

            # reshape from [samples, timesteps] into [samples, timesteps, features]
            n_features = 1
            X = X.reshape((X.shape[0], X.shape[1], n_features))

            model = Sequential()
            model.add(LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
            model.add(Dense(1))
            model.compile(optimizer='adam', loss='mse')

            # fit model
            model.fit(X, y, epochs=200, verbose=0)

            # demonstrate prediction
            x_input = array(rent_rate[-5:])
            x_input = x_input.reshape((1, n_steps, n_features))
            yhat = model.predict(x_input, verbose=0)
            add[column] = yhat.tolist()[0][0]
        # convert dict to dataframe
        Data = pd.DataFrame.from_dict(add, orient='index')


        # convert dataframe to csv
        mypath = f"Final_Score/LSTM/Backtesting/Boston"
        if not os.path.isdir(mypath):
            os.makedirs(mypath)
        Data.to_csv(f"{mypath}/Boston_{date}.csv", index=True)

NameError: name 'collect' is not defined

In [25]:
X

array([], dtype=float64)

## Backtest individual teams

In [ ]:
#obtain list of dates
directorys = ["Boston Celtics"]


for directory in directorys:
    list_dates = []
    for filename in os.listdir(directory):
        if filename.endswith(".csv"):
            list_dates.append(filename)
    # create dictionary 
    final_data = {}
    
    # reads in each csv
    for i in list_dates:
        data = pd.read_csv(f"{directory}/{i}", index_col=0)

        #gathers data and adds to dict
        date = data["Date"].tolist()[0]
        data[date] = data["Score"]
        final_data[date] = data[date]
    # convert dict to dataframe
    data_df = pd.DataFrame(final_data)
    
    
    tester = pd.DataFrame.transpose(data_df)
    columns = tester.columns.tolist()
    
    #create dict
    final_result = {}
    
    add = {}

    #iterate through index
    for column in columns:
        print(column)

    # univariate data prep LSTM
        from numpy import array

        # split sequence
        def split_sequence(sequence, n_steps):
            X, y = list(), list()
            for i in range(len(sequence)):
                # find end of pattern 
                end_ix = i + n_steps
                #check if beyond sequence to break
                if end_ix > len(sequence)-1:
                    break
                #gather input and output parts of the pattern
                seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
                X.append(seq_x)
                y.append(seq_y)
            return array(X), array(y)
        # sequence 
        rent_rate = list(tester[column].dropna())
        # number of steps
        n_steps = 3
        if len(rent_rate) < 5:
            continue
        X, y = split_sequence(rent_rate, n_steps)
        # summarize the data
        for i in range(len(X)):
            print(X[i], y[i])

        # reshape from [samples, timesteps] into [samples, timesteps, features]
        n_features = 1
        X = X.reshape((X.shape[0], X.shape[1], n_features))

        model = Sequential()
        model.add(LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
        model.add(Dense(1))
        model.compile(optimizer='adam', loss='mse')

        # fit model
        model.fit(X, y, epochs=200, verbose=0)

        # demonstrate prediction
        x_input = array(rent_rate[-3:])
        x_input = x_input.reshape((1, n_steps, n_features))
        yhat = model.predict(x_input, verbose=0)
        add[column] = yhat.tolist()[0][0]
    # convert dict to dataframe
    Data = pd.DataFrame.from_dict(add, orient='index')

    
    # convert dataframe to csv
    mypath = f"Final_Score/LSTM/{directory}"
    if not os.path.isdir(mypath):
        os.makedirs(mypath)
    Data.to_csv(f"{mypath}/{directory}.csv", index=True)

# Multiple Input Series

In [61]:
eff = pd.read_csv("Team_defensive_efficency.csv")

efficiency = {}

for name in opponents:
    team = opponents[name]
    team_name = team.split(" ")
    
    team_opp = team_name[0]
    
    if team_name[0] == ("Golden" or "New"):
        team_opp = f"{team_name[0]} {team_name[1]}"
    
    if team_name[0] == "Los":
        team_opp = f"LA {team_name[2]}"

    
    efficiency[name] = eff.loc[eff["Unnamed: 0"] == team_opp]["2021"].values[0]
    
eff_df = pd.DataFrame.transpose(pd.DataFrame.from_dict(efficiency, orient="index"))

eff_df.index = ["Efficiency"]

data_efficiency_df = data_df.append(eff_df)

data_efficiency_df.tail()

/var/folders/g3/164q6cz52jv0sjllnsg7jdsm0000gn/T/ipykernel_28858/1235662510.py:24: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data_efficiency_df = data_df.append(eff_df)


06/16/2022             06/02/2022  \
Payton Pritchard                      2.25                   19.5   
Robert Williams III                  30.75                   24.5   
Sam Hauser                             0.0                    0.0   
0                    Golden State Warriors  Golden State Warriors   
Efficiency                           1.042                  1.042   

                                06/10/2022             06/05/2022  \
Payton Pritchard                      1.75                   13.5   
Robert Williams III                   34.0                   10.0   
Sam Hauser                             NaN                    5.0   
0                    Golden State Warriors  Golden State Warriors   
Efficiency                           1.042                  1.042   

                                06/13/2022     04/17/2022  05/25/2022  \
Payton Pritchard                      0.75           4.75        1.25   
Robert Williams III                   23.0            NaN        26.5   
Sam Hauser                             1.5            NaN         NaN   
0                    Golden State Warriors  Brooklyn Nets  Miami Heat   
Efficiency                           1.042          1.093       1.052   

                     05/19/2022  05/27/2022  05/23/2022  ...       05/13/2022  \
Payton Pritchard           18.5         0.0        26.0  ...              3.5   
Robert Williams III        17.5       18.75       27.25  ...              NaN   
Sam Hauser                  NaN         NaN         NaN  ...              NaN   
0                    Miami Heat  Miami Heat  Miami Heat  ...  Milwaukee Bucks   
Efficiency                1.052       1.052       1.052  ...            1.075   

                     05/17/2022       05/03/2022  05/29/2022       05/15/2022  \
Payton Pritchard          33.75            14.75         0.0            26.75   
Robert Williams III       34.25             20.0        6.75              NaN   
Sam Hauser                  NaN             3.25         NaN              NaN   
0                    Miami Heat  Milwaukee Bucks  Miami Heat  Milwaukee Bucks   
Efficiency                1.052            1.075       1.052            1.075   

                          05/01/2022             06/08/2022     04/25/2022  \
Payton Pritchard                 9.5                    4.5           4.25   
Robert Williams III             24.0                   34.5          10.75   
Sam Hauser                       0.0                    0.0            NaN   
0                    Milwaukee Bucks  Golden State Warriors  Brooklyn Nets   
Efficiency                     1.075                  1.042          1.093   

                        04/20/2022     04/23/2022  
Payton Pritchard              16.0           14.5  
Robert Williams III            NaN            8.0  
Sam Hauser                     NaN            NaN  
0                    Brooklyn Nets  Brooklyn Nets  
Efficiency                   1.093          1.093  

[5 rows x 24 columns]

In [65]:
tester_eff = pd.DataFrame.transpose(data_efficiency_df)
tester_eff.drop(columns=[0], inplace=True)
tester_eff.head()

Aaron Nesmith Al Horford Daniel Theis Derrick White Grant Williams  \
06/16/2022           0.0       46.0          NaN          5.75           7.25   
06/02/2022           0.0       42.0          5.5         28.25           8.25   
06/10/2022           NaN       24.0          NaN         20.75           4.75   
06/05/2022          11.5       14.5         9.25          25.5          11.25   
06/13/2022          4.25      21.75          NaN          8.75          11.25   

           Jaylen Brown Jayson Tatum Juwan Morgan Luke Kornet Malik Fitts  \
06/16/2022        49.25        33.25          0.0        0.75         NaN   
06/02/2022        45.25        39.25          0.0         NaN         0.0   
06/10/2022         33.5        52.75          NaN         NaN         NaN   
06/05/2022         29.5         43.0          NaN         3.5         3.5   
06/13/2022        34.75         46.0         1.25        4.75         NaN   

           Marcus Smart Nik Stauskas Payton Pritchard Robert Williams III  \
06/16/2022         33.0          0.0             2.25               30.75   
06/02/2022        36.25          0.0             19.5                24.5   
06/10/2022         39.0          NaN             1.75                34.0   
06/05/2022         11.5         8.75             13.5                10.0   
06/13/2022        26.25          0.0             0.75                23.0   

           Sam Hauser Efficiency  
06/16/2022        0.0      1.042  
06/02/2022        0.0      1.042  
06/10/2022        NaN      1.042  
06/05/2022        5.0      1.042  
06/13/2022        1.5      1.042

In [90]:
tester_eff["Aaron Nesmith"].dropna()

06/16/2022      0.0
06/02/2022      0.0
06/05/2022     11.5
06/13/2022     4.25
05/25/2022      0.0
05/19/2022     1.25
05/27/2022      0.0
05/23/2022    10.25
05/21/2022      0.0
05/13/2022     1.25
05/17/2022     8.75
05/03/2022     1.25
05/15/2022     4.75
05/01/2022     2.75
06/08/2022     1.25
Name: Aaron Nesmith, dtype: object

In [97]:
hstack((rent_rate, eff, predict)) 

array([[0.0, 1.042, 0.0],
       [0.0, 1.042, 0.0],
       [11.5, 1.042, 11.5],
       [4.25, 1.042, 4.25],
       [0.0, 1.052, 0.0],
       [1.25, 1.052, 1.25],
       [0.0, 1.052, 0.0],
       [10.25, 1.052, 10.25],
       [0.0, 1.052, 0.0],
       [1.25, 1.075, 1.25],
       [8.75, 1.052, 8.75],
       [1.25, 1.075, 1.25],
       [4.75, 1.075, 4.75],
       [2.75, 1.075, 2.75],
       [1.25, 1.042, 1.25]], dtype=object)

In [93]:
eff

[1.042,
 1.042,
 1.042,
 1.042,
 1.052,
 1.052,
 1.052,
 1.052,
 1.052,
 1.075,
 1.052,
 1.075,
 1.075,
 1.075,
 1.042]

In [179]:
add = {}

#iterate through index
for column in columns:
    print(column)
    
# univariate data prep LSTM
    from numpy import array

    # split sequence
    def split_sequence(sequence, n_steps):
        X, y = list(), list()
        for i in range(len(sequence)):
            # find end of pattern 
            end_ix = i + n_steps
            #check if beyond sequence to break
            if end_ix > len(sequence):
                break
            #gather input and output parts of the pattern
            seq_x, seq_y = sequence[i:end_ix, :-1], sequence[end_ix-1, -1]
            X.append(seq_x)
            y.append(seq_y)
        return array(X), array(y)
    # sequence 
    df = tester_eff[[column, "Efficiency"]].dropna()
    
    name = df.columns[0]
    
    rent_rate = array(df[name])
    
    eff = array(df["Efficiency"])
    
    predict = rent_rate
    
    
    # convert to [rows, columns] structure
    rent_rate = rent_rate.reshape((len(rent_rate), 1))
    eff = eff.reshape((len(eff), 1))
    predict = predict.reshape((len(predict), 1))
    
    # number of steps
    n_steps = 3
    if len(rent_rate) < 5:
        continue   
        
    # horizontally stack columns
    dataset = hstack((rent_rate, eff, predict))    
        
    X, y = split_sequence(dataset, n_steps)
    
    X = X.astype(float)
    # summarize the data
    for i in range(len(X)):
        print(X[i], y[i])

    # reshape from [samples, timesteps] into [samples, timesteps, features]
    n_features = X.shape[2]

    model = Sequential()
    model.add(LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
    model.add(Dense(1))
    model.compile(optimizer='adam', loss='mse')

    # fit model
    model.fit(X, y, epochs=200, verbose=0)
    
    rent = []
    pred = []
    for i in rent_rate[-3:]:
        rent.append(i[0])
        pred.append(i[0])
    eff_pred = []
    for i in eff[-3:]:
        eff_pred.append(i[0])

    # demonstrate prediction
    x_input = array([[rent[0], eff_pred[0]], [rent[1], eff_pred[1]], [rent[2], eff_pred[2]]])
    x_input = x_input.reshape((1, n_steps, n_features))
    yhat = model.predict(x_input, verbose=0)
    add[column] = yhat.tolist()[0][0]

Aaron Nesmith
[[ 0.     1.042]
 [ 0.     1.042]
 [11.5    1.042]] 11.5
[[ 0.     1.042]
 [11.5    1.042]
 [ 4.25   1.042]] 4.25
[[11.5    1.042]
 [ 4.25   1.042]
 [ 0.     1.052]] 0.0
[[4.25  1.042]
 [0.    1.052]
 [1.25  1.052]] 1.25
[[0.    1.052]
 [1.25  1.052]
 [0.    1.052]] 0.0
[[ 1.25   1.052]
 [ 0.     1.052]
 [10.25   1.052]] 10.25
[[ 0.     1.052]
 [10.25   1.052]
 [ 0.     1.052]] 0.0
[[10.25   1.052]
 [ 0.     1.052]
 [ 1.25   1.075]] 1.25
[[0.    1.052]
 [1.25  1.075]
 [8.75  1.052]] 8.75
[[1.25  1.075]
 [8.75  1.052]
 [1.25  1.075]] 1.25
[[8.75  1.052]
 [1.25  1.075]
 [4.75  1.075]] 4.75
[[1.25  1.075]
 [4.75  1.075]
 [2.75  1.075]] 2.75
[[4.75  1.075]
 [2.75  1.075]
 [1.25  1.042]] 1.25


2022-09-10 21:42:47.543408: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Al Horford
[[46.     1.042]
 [42.     1.042]
 [24.     1.042]] 24.0
[[42.     1.042]
 [24.     1.042]
 [14.5    1.042]] 14.5
[[24.     1.042]
 [14.5    1.042]
 [21.75   1.042]] 21.75
[[14.5    1.042]
 [21.75   1.042]
 [44.25   1.093]] 44.25
[[21.75   1.042]
 [44.25   1.093]
 [38.25   1.052]] 38.25
[[44.25   1.093]
 [38.25   1.052]
 [21.75   1.052]] 21.75
[[38.25   1.052]
 [21.75   1.052]
 [20.75   1.052]] 20.75
[[21.75   1.052]
 [20.75   1.052]
 [34.25   1.052]] 34.25
[[20.75   1.052]
 [34.25   1.052]
 [48.     1.052]] 48.0
[[34.25   1.052]
 [48.     1.052]
 [48.5    1.075]] 48.5
[[48.     1.052]
 [48.5    1.075]
 [34.5    1.075]] 34.5
[[48.5    1.075]
 [34.5    1.075]
 [55.5    1.075]] 55.5
[[34.5    1.075]
 [55.5    1.075]
 [28.5    1.075]] 28.5
[[55.5    1.075]
 [28.5    1.075]
 [39.25   1.075]] 39.25
[[28.5    1.075]
 [39.25   1.075]
 [33.5    1.052]] 33.5
[[39.25   1.075]
 [33.5    1.052]
 [29.5    1.075]] 29.5
[[33.5    1.052]
 [29.5    1.075]
 [36.     1.075]] 36.0
[[29.5    1.0

2022-09-10 21:42:50.945458: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 21:42:51.370256: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Daniel Theis
[[ 5.5    1.042]
 [ 9.25   1.042]
 [13.     1.093]] 13.0
[[ 9.25   1.042]
 [13.     1.093]
 [ 4.75   1.052]] 4.75
[[13.     1.093]
 [ 4.75   1.052]
 [ 7.75   1.052]] 7.75
[[4.75  1.052]
 [7.75  1.052]
 [5.25  1.052]] 5.25
[[7.75  1.052]
 [5.25  1.052]
 [2.25  1.075]] 2.25
[[ 5.25   1.052]
 [ 2.25   1.075]
 [14.75   1.075]] 14.75
[[ 2.25   1.075]
 [14.75   1.075]
 [ 0.75   1.075]] 0.75
[[14.75   1.075]
 [ 0.75   1.075]
 [ 6.5    1.075]] 6.5
[[ 0.75   1.075]
 [ 6.5    1.075]
 [18.     1.052]] 18.0
[[ 6.5    1.075]
 [18.     1.052]
 [ 9.75   1.075]] 9.75
[[18.     1.052]
 [ 9.75   1.075]
 [ 6.     1.075]] 6.0
[[ 9.75   1.075]
 [ 6.     1.075]
 [20.5    1.093]] 20.5
[[ 6.     1.075]
 [20.5    1.093]
 [26.5    1.093]] 26.5
[[20.5    1.093]
 [26.5    1.093]
 [20.     1.093]] 20.0


2022-09-10 21:42:54.903701: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 21:42:55.339240: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Derrick White
[[ 5.75   1.042]
 [28.25   1.042]
 [20.75   1.042]] 20.75
[[28.25   1.042]
 [20.75   1.042]
 [25.5    1.042]] 25.5
[[20.75   1.042]
 [25.5    1.042]
 [ 8.75   1.042]] 8.75
[[25.5    1.042]
 [ 8.75   1.042]
 [22.25   1.093]] 22.25
[[ 8.75   1.042]
 [22.25   1.093]
 [27.25   1.052]] 27.25
[[22.25   1.093]
 [27.25   1.052]
 [43.25   1.052]] 43.25
[[27.25   1.052]
 [43.25   1.052]
 [39.     1.052]] 39.0
[[43.25   1.052]
 [39.     1.052]
 [ 8.     1.052]] 8.0
[[39.     1.052]
 [ 8.     1.052]
 [23.     1.075]] 23.0
[[ 8.     1.052]
 [23.     1.075]
 [28.25   1.075]] 28.25
[[23.     1.075]
 [28.25   1.075]
 [19.5    1.075]] 19.5
[[28.25   1.075]
 [19.5    1.075]
 [22.75   1.075]] 22.75
[[19.5    1.075]
 [22.75   1.075]
 [10.     1.052]] 10.0
[[22.75   1.075]
 [10.     1.052]
 [13.5    1.075]] 13.5
[[10.     1.052]
 [13.5    1.075]
 [14.75   1.052]] 14.75
[[13.5    1.075]
 [14.75   1.052]
 [ 9.5    1.075]] 9.5
[[14.75   1.052]
 [ 9.5    1.075]
 [16.5    1.075]] 16.5
[[ 9.5    1.

2022-09-10 21:42:58.863279: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 21:42:59.298813: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Grant Williams
[[7.25  1.042]
 [8.25  1.042]
 [4.75  1.042]] 4.75
[[ 8.25   1.042]
 [ 4.75   1.042]
 [11.25   1.042]] 11.25
[[ 4.75   1.042]
 [11.25   1.042]
 [11.25   1.042]] 11.25
[[11.25   1.042]
 [11.25   1.042]
 [13.     1.093]] 13.0
[[11.25   1.042]
 [13.     1.093]
 [12.5    1.052]] 12.5
[[13.     1.093]
 [12.5    1.052]
 [27.     1.052]] 27.0
[[12.5    1.052]
 [27.     1.052]
 [ 6.5    1.052]] 6.5
[[27.     1.052]
 [ 6.5    1.052]
 [16.25   1.052]] 16.25
[[ 6.5    1.052]
 [16.25   1.052]
 [20.75   1.052]] 20.75
[[16.25   1.052]
 [20.75   1.052]
 [13.5    1.075]] 13.5
[[20.75   1.052]
 [13.5    1.075]
 [ 3.     1.075]] 3.0
[[13.5    1.075]
 [ 3.     1.075]
 [25.5    1.075]] 25.5
[[ 3.     1.075]
 [25.5    1.075]
 [13.25   1.075]] 13.25
[[25.5    1.075]
 [13.25   1.075]
 [12.75   1.052]] 12.75
[[13.25   1.075]
 [12.75   1.052]
 [33.25   1.075]] 33.25
[[12.75   1.052]
 [33.25   1.075]
 [19.5    1.052]] 19.5
[[33.25   1.075]
 [19.5    1.052]
 [41.5    1.075]] 41.5
[[19.5    1.052]


2022-09-10 21:43:02.711567: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 21:43:03.141267: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Jaylen Brown
[[49.25   1.042]
 [45.25   1.042]
 [33.5    1.042]] 33.5
[[45.25   1.042]
 [33.5    1.042]
 [29.5    1.042]] 29.5
[[33.5    1.042]
 [29.5    1.042]
 [34.75   1.042]] 34.75
[[29.5    1.042]
 [34.75   1.042]
 [45.25   1.093]] 45.25
[[34.75   1.042]
 [45.25   1.093]
 [36.     1.052]] 36.0
[[45.25   1.093]
 [36.     1.052]
 [40.     1.052]] 40.0
[[36.     1.052]
 [40.     1.052]
 [37.5    1.052]] 37.5
[[40.     1.052]
 [37.5    1.052]
 [23.75   1.052]] 23.75
[[37.5    1.052]
 [23.75   1.052]
 [54.75   1.052]] 54.75
[[23.75   1.052]
 [54.75   1.052]
 [25.25   1.075]] 25.25
[[54.75   1.052]
 [25.25   1.075]
 [47.5    1.075]] 47.5
[[25.25   1.075]
 [47.5    1.075]
 [48.5    1.075]] 48.5
[[47.5    1.075]
 [48.5    1.075]
 [37.25   1.075]] 37.25
[[48.5    1.075]
 [37.25   1.075]
 [44.     1.052]] 44.0
[[37.25   1.075]
 [44.     1.052]
 [54.5    1.075]] 54.5
[[44.     1.052]
 [54.5    1.075]
 [39.     1.052]] 39.0
[[54.5    1.075]
 [39.     1.052]
 [33.     1.075]] 33.0
[[39.     1.

2022-09-10 21:43:06.471885: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 21:43:07.268861: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Jayson Tatum
[[33.25   1.042]
 [39.25   1.042]
 [52.75   1.042]] 52.75
[[39.25   1.042]
 [52.75   1.042]
 [43.     1.042]] 43.0
[[52.75   1.042]
 [43.     1.042]
 [46.     1.042]] 46.0
[[43.     1.042]
 [46.     1.042]
 [53.     1.093]] 53.0
[[46.     1.042]
 [53.     1.093]
 [49.     1.052]] 49.0
[[53.     1.093]
 [49.     1.052]
 [43.25   1.052]] 43.25
[[49.     1.052]
 [43.25   1.052]
 [51.75   1.052]] 51.75
[[43.25   1.052]
 [51.75   1.052]
 [51.5    1.052]] 51.5
[[51.75   1.052]
 [51.5    1.052]
 [21.     1.052]] 21.0
[[51.5    1.052]
 [21.     1.052]
 [54.25   1.075]] 54.25
[[21.     1.052]
 [54.25   1.075]
 [52.     1.075]] 52.0
[[54.25   1.075]
 [52.     1.075]
 [24.25   1.075]] 24.25
[[52.     1.075]
 [24.25   1.075]
 [66.75   1.075]] 66.75
[[24.25   1.075]
 [66.75   1.075]
 [55.5    1.052]] 55.5
[[66.75   1.075]
 [55.5    1.052]
 [53.25   1.075]] 53.25
[[55.5    1.052]
 [53.25   1.075]
 [54.5    1.052]] 54.5
[[53.25   1.075]
 [54.5    1.052]
 [43.5    1.075]] 43.5
[[54.5    1

2022-09-10 21:43:10.631183: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 21:43:11.046936: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Juwan Morgan
[[0.    1.042]
 [0.    1.042]
 [1.25  1.042]] 1.25
[[0.    1.042]
 [1.25  1.042]
 [0.    1.052]] 0.0
[[1.25  1.042]
 [0.    1.052]
 [2.25  1.052]] 2.25
[[0.    1.052]
 [2.25  1.052]
 [0.    1.052]] 0.0
[[2.25  1.052]
 [0.    1.052]
 [1.25  1.052]] 1.25
[[0.    1.052]
 [1.25  1.052]
 [0.    1.075]] 0.0
[[1.25  1.052]
 [0.    1.075]
 [0.    1.042]] 0.0


2022-09-10 21:43:14.392428: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 21:43:14.801588: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Luke Kornet
[[0.75  1.042]
 [3.5   1.042]
 [4.75  1.042]] 4.75
[[3.5   1.042]
 [4.75  1.042]
 [0.    1.052]] 0.0
[[4.75  1.042]
 [0.    1.052]
 [4.5   1.052]] 4.5
[[0.    1.052]
 [4.5   1.052]
 [0.    1.052]] 0.0
[[4.5   1.052]
 [0.    1.052]
 [1.25  1.075]] 1.25
[[0.    1.052]
 [1.25  1.075]
 [0.    1.075]] 0.0
[[1.25  1.075]
 [0.    1.075]
 [0.    1.075]] 0.0


2022-09-10 21:43:18.117627: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 21:43:18.538391: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Malik Fitts
[[0.    1.042]
 [3.5   1.042]
 [0.    1.052]] 0.0
[[3.5   1.042]
 [0.    1.052]
 [0.    1.052]] 0.0
[[0.    1.052]
 [0.    1.052]
 [0.    1.052]] 0.0
[[0.    1.052]
 [0.    1.052]
 [1.25  1.075]] 1.25
[[0.    1.052]
 [1.25  1.075]
 [3.5   1.075]] 3.5
[[1.25  1.075]
 [3.5   1.075]
 [3.25  1.075]] 3.25
[[3.5   1.075]
 [3.25  1.075]
 [0.    1.042]] 0.0


2022-09-10 21:43:21.839568: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 21:43:22.602733: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Marcus Smart
[[33.     1.042]
 [36.25   1.042]
 [39.     1.042]] 39.0
[[36.25   1.042]
 [39.     1.042]
 [11.5    1.042]] 11.5
[[39.     1.042]
 [11.5    1.042]
 [26.25   1.042]] 26.25
[[11.5    1.042]
 [26.25   1.042]
 [42.25   1.093]] 42.25
[[26.25   1.042]
 [42.25   1.093]
 [17.25   1.052]] 17.25
[[42.25   1.093]
 [17.25   1.052]
 [63.25   1.052]] 63.25
[[17.25   1.052]
 [63.25   1.052]
 [25.     1.052]] 25.0
[[63.25   1.052]
 [25.     1.052]
 [30.     1.052]] 30.0
[[25.     1.052]
 [30.     1.052]
 [36.     1.075]] 36.0
[[30.     1.052]
 [36.     1.075]
 [27.5    1.075]] 27.5
[[36.     1.075]
 [27.5    1.075]
 [15.5    1.075]] 15.5
[[27.5    1.075]
 [15.5    1.075]
 [40.25   1.075]] 40.25
[[15.5    1.075]
 [40.25   1.075]
 [47.75   1.052]] 47.75
[[40.25   1.075]
 [47.75   1.052]
 [38.25   1.075]] 38.25
[[47.75   1.052]
 [38.25   1.075]
 [23.25   1.075]] 23.25
[[38.25   1.075]
 [23.25   1.075]
 [39.25   1.042]] 39.25
[[23.25   1.075]
 [39.25   1.042]
 [43.75   1.093]] 43.75
[[39.25 

2022-09-10 21:43:25.898532: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 21:43:26.308577: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Nik Stauskas
[[0.    1.042]
 [0.    1.042]
 [8.75  1.042]] 8.75
[[0.    1.042]
 [8.75  1.042]
 [0.    1.042]] 0.0
[[8.75  1.042]
 [0.    1.042]
 [0.    1.052]] 0.0
[[0.    1.042]
 [0.    1.052]
 [7.75  1.052]] 7.75
[[0.    1.052]
 [7.75  1.052]
 [2.    1.052]] 2.0
[[7.75  1.052]
 [2.    1.052]
 [3.5   1.052]] 3.5
[[2.    1.052]
 [3.5   1.052]
 [2.    1.075]] 2.0
[[3.5   1.052]
 [2.    1.075]
 [0.    1.075]] 0.0
[[2.    1.075]
 [0.    1.075]
 [1.5   1.075]] 1.5
[[0.    1.075]
 [1.5   1.075]
 [0.    1.075]] 0.0
[[1.5   1.075]
 [0.    1.075]
 [0.    1.042]] 0.0


2022-09-10 21:43:29.657075: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 21:43:30.073591: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Payton Pritchard
[[ 2.25   1.042]
 [19.5    1.042]
 [ 1.75   1.042]] 1.75
[[19.5    1.042]
 [ 1.75   1.042]
 [13.5    1.042]] 13.5
[[ 1.75   1.042]
 [13.5    1.042]
 [ 0.75   1.042]] 0.75
[[13.5    1.042]
 [ 0.75   1.042]
 [ 4.75   1.093]] 4.75
[[0.75  1.042]
 [4.75  1.093]
 [1.25  1.052]] 1.25
[[ 4.75   1.093]
 [ 1.25   1.052]
 [18.5    1.052]] 18.5
[[ 1.25   1.052]
 [18.5    1.052]
 [ 0.     1.052]] 0.0
[[18.5    1.052]
 [ 0.     1.052]
 [26.     1.052]] 26.0
[[ 0.     1.052]
 [26.     1.052]
 [ 9.5    1.052]] 9.5
[[26.     1.052]
 [ 9.5    1.052]
 [11.75   1.075]] 11.75
[[ 9.5    1.052]
 [11.75   1.075]
 [ 8.     1.075]] 8.0
[[11.75   1.075]
 [ 8.     1.075]
 [ 7.     1.075]] 7.0
[[8.    1.075]
 [7.    1.075]
 [3.5   1.075]] 3.5
[[ 7.     1.075]
 [ 3.5    1.075]
 [33.75   1.052]] 33.75
[[ 3.5    1.075]
 [33.75   1.052]
 [14.75   1.075]] 14.75
[[33.75   1.052]
 [14.75   1.075]
 [ 0.     1.052]] 0.0
[[14.75   1.075]
 [ 0.     1.052]
 [26.75   1.075]] 26.75
[[ 0.     1.052]
 [26.75   1

2022-09-10 21:43:33.413603: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 21:43:33.823156: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Robert Williams III
[[30.75   1.042]
 [24.5    1.042]
 [34.     1.042]] 34.0
[[24.5    1.042]
 [34.     1.042]
 [10.     1.042]] 10.0
[[34.     1.042]
 [10.     1.042]
 [23.     1.042]] 23.0
[[10.     1.042]
 [23.     1.042]
 [26.5    1.052]] 26.5
[[23.     1.042]
 [26.5    1.052]
 [17.5    1.052]] 17.5
[[26.5    1.052]
 [17.5    1.052]
 [18.75   1.052]] 18.75
[[17.5    1.052]
 [18.75   1.052]
 [27.25   1.052]] 27.25
[[18.75   1.052]
 [27.25   1.052]
 [32.25   1.075]] 32.25
[[27.25   1.052]
 [32.25   1.075]
 [34.25   1.052]] 34.25
[[32.25   1.075]
 [34.25   1.052]
 [20.     1.075]] 20.0
[[34.25   1.052]
 [20.     1.075]
 [ 6.75   1.052]] 6.75
[[20.     1.075]
 [ 6.75   1.052]
 [24.     1.075]] 24.0
[[ 6.75   1.052]
 [24.     1.075]
 [34.5    1.042]] 34.5
[[24.     1.075]
 [34.5    1.042]
 [10.75   1.093]] 10.75
[[34.5    1.042]
 [10.75   1.093]
 [ 8.     1.093]] 8.0


2022-09-10 21:43:37.176371: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 21:43:37.589218: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Sam Hauser
[[0.    1.042]
 [0.    1.042]
 [5.    1.042]] 5.0
[[0.    1.042]
 [5.    1.042]
 [1.5   1.042]] 1.5
[[5.    1.042]
 [1.5   1.042]
 [3.25  1.075]] 3.25
[[1.5   1.042]
 [3.25  1.075]
 [0.    1.075]] 0.0
[[3.25  1.075]
 [0.    1.075]
 [0.    1.042]] 0.0


2022-09-10 21:43:41.018920: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 21:43:41.829910: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 21:43:45.211773: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


In [180]:
add

{'Aaron Nesmith': 1.1010284423828125,
 'Al Horford': 15.41996955871582,
 'Daniel Theis': 20.017879486083984,
 'Derrick White': 12.299777030944824,
 'Grant Williams': 16.760189056396484,
 'Jaylen Brown': 38.3687858581543,
 'Jayson Tatum': 65.13274383544922,
 'Juwan Morgan': -0.02259661629796028,
 'Luke Kornet': -0.05909275263547897,
 'Malik Fitts': 0.002770889550447464,
 'Marcus Smart': 30.925310134887695,
 'Nik Stauskas': 0.03696215897798538,
 'Payton Pritchard': 14.317920684814453,
 'Robert Williams III': 8.039493560791016,
 'Sam Hauser': -0.002224911004304886}

# Stacked LSTM

In [42]:
add = {}

from keras.layers import Bidirectional

#iterate through index
for column in columns:
    print(column)
    
# univariate data prep LSTM
    from numpy import array

    # split sequence
    def split_sequence(sequence, n_steps):
        X, y = list(), list()
        for i in range(len(sequence)):
            # find end of pattern 
            end_ix = i + n_steps
            #check if beyond sequence to break
            if end_ix > len(sequence)-1:
                break
            #gather input and output parts of the pattern
            seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
            X.append(seq_x)
            y.append(seq_y)
        return array(X), array(y)
    # sequence 
    rent_rate = list(tester[column].dropna())
    # number of steps
    n_steps = 3
    if len(rent_rate) < 4:
        continue
    X, y = split_sequence(rent_rate, n_steps)
    # summarize the data
    for i in range(len(X)):
        print(X[i], y[i])

    # reshape from [samples, timesteps] into [samples, timesteps, features]
    n_features = 1
    X = X.reshape((X.shape[0], X.shape[1], n_features))

    model = Sequential()
    model.add(Bidirectional(LSTM(50, activation='relu', input_shape=(n_steps, n_features))))
    model.add(Dense(1))
    model.compile(optimizer='adam', loss='mse')

    # fit model
    model.fit(X, y, epochs=200, verbose=0)

    # demonstrate prediction
    x_input = array(rent_rate[-3:])
    x_input = x_input.reshape((1, n_steps, n_features))
    yhat = model.predict(x_input, verbose=0)
    add[column] = yhat.tolist()[0][0]

Anthony Davis
Austin Reaves
[72.   36.75 17.75] 20.5
[36.75 17.75 20.5 ] 7.5
[17.75 20.5   7.5 ] 21.25
[20.5   7.5  21.25] 20.5


2022-10-15 16:27:17.741200: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Cole Swider
[15.75 16.   30.75] 11.0
[16.   30.75 11.  ] 14.5
[30.75 11.   14.5 ] 12.5


2022-10-15 16:27:25.078307: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-10-15 16:27:26.443326: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


D.J. Augustin
Damian Jones
[9.   8.   1.25] 11.0
[ 8.    1.25 11.  ] 11.5
[ 1.25 11.   11.5 ] 5.25


2022-10-15 16:27:34.643648: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-10-15 16:27:35.620046: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Dennis Schroder
Dwayne Bacon
Jay Huff
Juan Toscano-Anderson
[15.5   9.5   8.25] 6.25
[9.5  8.25 6.25] 18.75


2022-10-15 16:27:44.065043: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-10-15 16:27:45.121223: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Kendrick Nunn
[29.25  9.   11.  ] 13.0
[ 9. 11. 13.] 37.0


2022-10-15 16:27:54.058362: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-10-15 16:27:55.603827: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


LeBron James
[36.25 44.75  7.75] 17.25


2022-10-15 16:28:04.481978: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-10-15 16:28:05.560839: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Lonnie Walker IV
Mac McClung
Malik Monk
Mason Jones
Matt Ryan
[ 4.75  1.   13.25] 13.0
[ 1.   13.25 13.  ] 23.75


2022-10-15 16:28:15.262362: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-10-15 16:28:16.777499: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Max Christie
[ 8.   11.5  18.25] 16.0
[11.5  18.25 16.  ] 4.75
[18.25 16.    4.75] 17.25


2022-10-15 16:28:26.908053: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-10-15 16:28:28.086431: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Nate Pierre-Louis
Patrick Beverley
[19.   27.   13.25] 7.25


2022-10-15 16:28:37.771937: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-10-15 16:28:39.240251: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Russell Westbrook
[23.   15.25 11.5 ] 3.25


2022-10-15 16:28:48.235387: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-10-15 16:28:49.299755: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Scotty Pippen Jr.
[10.25  6.25 39.  ] 11.5
[ 6.25 39.   11.5 ] 15.5
[39.  11.5 15.5] 3.75


2022-10-15 16:28:58.666689: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-10-15 16:28:59.703576: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Shaquille Harrison
Stanley Johnson
Talen Horton-Tucker
Thomas Bryant
[ 7.75  5.75 31.75] 12.25
[ 5.75 31.75 12.25] 13.5
[31.75 12.25 13.5 ] 14.25


2022-10-15 16:29:08.866311: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-10-15 16:29:11.092037: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Wayne Ellington
Wenyen Gabriel
[35.    6.25  8.5 ] 6.75
[6.25 8.5  6.75] 27.5
[ 8.5   6.75 27.5 ] 8.0
[ 6.75 27.5   8.  ] 10.75


2022-10-15 16:29:20.951066: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-10-15 16:29:22.006645: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-10-15 16:29:31.258317: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


In [43]:
add

{'Austin Reaves': 19.070512771606445,
 'Cole Swider': 7.0764265060424805,
 'Damian Jones': 17.173702239990234,
 'Juan Toscano-Anderson': 30.316635131835938,
 'Kendrick Nunn': 114.31356048583984,
 'LeBron James': 11.993985176086426,
 'Matt Ryan': 57.7443733215332,
 'Max Christie': 27.625999450683594,
 'Patrick Beverley': 5.453878402709961,
 'Russell Westbrook': 1.5929194688796997,
 'Scotty Pippen Jr.': 4.623406410217285,
 'Thomas Bryant': 9.415352821350098,
 'Wenyen Gabriel': 13.238883018493652}

In [46]:
add = {}

#iterate through index
for column in columns:
    print(column)
    
# univariate data prep LSTM
    from numpy import array

    # split sequence
    def split_sequence(sequence, n_steps):
        X, y = list(), list()
        for i in range(len(sequence)):
            # find end of pattern 
            end_ix = i + n_steps
            #check if beyond sequence to break
            if end_ix > len(sequence)-1:
                break
            #gather input and output parts of the pattern
            seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
            X.append(seq_x)
            y.append(seq_y)
        return array(X), array(y)
    # sequence 
    rent_rate = list(tester[column].dropna())
    # number of steps
    n_steps = 2
    if len(rent_rate) < 3:
        continue
    X, y = split_sequence(rent_rate, n_steps)
    # summarize the data
    for i in range(len(X)):
        print(X[i], y[i])

    # reshape from [samples, timesteps] into [samples, timesteps, features]
    n_features = 1
    X = X.reshape((X.shape[0], X.shape[1], n_features))

    model = Sequential()
    model.add(LSTM(50, activation='relu', return_sequences=True,input_shape=(n_steps, n_features)))
    model.add(LSTM(50, activation='relu'))
    model.add(Dense(1))
    model.compile(optimizer='adam', loss='mse')

    # fit model
    model.fit(X, y, epochs=200, verbose=0)

    # demonstrate prediction
    x_input = array(rent_rate[-2:])
    x_input = x_input.reshape((1, n_steps, n_features))
    yhat = model.predict(x_input, verbose=0)
    add[column] = yhat.tolist()[0][0]

Anthony Davis
[46.75 30.75] 38.75


2022-10-15 16:33:22.587388: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Austin Reaves
[72.   36.75] 17.75
[36.75 17.75] 20.5
[17.75 20.5 ] 7.5
[20.5  7.5] 21.25
[ 7.5  21.25] 20.5


2022-10-15 16:33:28.400792: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-10-15 16:33:29.390096: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Cole Swider
[15.75 16.  ] 30.75
[16.   30.75] 11.0
[30.75 11.  ] 14.5
[11.  14.5] 12.5


2022-10-15 16:33:35.935012: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-10-15 16:33:37.325055: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


D.J. Augustin
Damian Jones
[9. 8.] 1.25
[8.   1.25] 11.0
[ 1.25 11.  ] 11.5
[11.  11.5] 5.25


2022-10-15 16:33:43.220038: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-10-15 16:33:44.169248: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Dennis Schroder
Dwayne Bacon
Jay Huff
[ 4.75 16.75] 12.5


2022-10-15 16:33:49.999049: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-10-15 16:33:51.346510: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Juan Toscano-Anderson
[15.5  9.5] 8.25
[9.5  8.25] 6.25
[8.25 6.25] 18.75


2022-10-15 16:33:57.196194: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-10-15 16:33:58.153184: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Kendrick Nunn
[29.25  9.  ] 11.0
[ 9. 11.] 13.0
[11. 13.] 37.0


2022-10-15 16:34:04.275369: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-10-15 16:34:05.253096: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


LeBron James
[36.25 44.75] 7.75
[44.75  7.75] 17.25


2022-10-15 16:34:11.397545: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-10-15 16:34:12.857546: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Lonnie Walker IV
[17.75 26.25] 21.0


2022-10-15 16:34:19.157696: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-10-15 16:34:20.154024: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Mac McClung
Malik Monk
Mason Jones
Matt Ryan
[4.75 1.  ] 13.25
[ 1.   13.25] 13.0
[13.25 13.  ] 23.75


2022-10-15 16:34:26.567832: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-10-15 16:34:27.958852: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Max Christie
[ 8.  11.5] 18.25
[11.5  18.25] 16.0
[18.25 16.  ] 4.75
[16.    4.75] 17.25


2022-10-15 16:34:34.603911: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-10-15 16:34:35.691825: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Nate Pierre-Louis
Patrick Beverley
[19. 27.] 13.25
[27.   13.25] 7.25


2022-10-15 16:34:42.252777: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-10-15 16:34:43.706482: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Russell Westbrook
[23.   15.25] 11.5
[15.25 11.5 ] 3.25


2022-10-15 16:34:50.374962: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-10-15 16:34:51.398845: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Scotty Pippen Jr.
[10.25  6.25] 39.0
[ 6.25 39.  ] 11.5
[39.  11.5] 15.5
[11.5 15.5] 3.75


2022-10-15 16:34:57.899747: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-10-15 16:34:58.897896: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Shaquille Harrison
Stanley Johnson
Talen Horton-Tucker
Thomas Bryant
[7.75 5.75] 31.75
[ 5.75 31.75] 12.25
[31.75 12.25] 13.5
[12.25 13.5 ] 14.25


2022-10-15 16:35:05.450171: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-10-15 16:35:06.973125: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Wayne Ellington
Wenyen Gabriel
[35.    6.25] 8.5
[6.25 8.5 ] 6.75
[8.5  6.75] 27.5
[ 6.75 27.5 ] 8.0
[27.5  8. ] 10.75


2022-10-15 16:35:14.433232: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-10-15 16:35:15.509974: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-10-15 16:35:22.227311: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


In [47]:
add

{'Anthony Davis': 27.944467544555664,
 'Austin Reaves': 8.387675285339355,
 'Cole Swider': 25.410066604614258,
 'Damian Jones': 8.89858627319336,
 'Jay Huff': 36.7367057800293,
 'Juan Toscano-Anderson': 7.188565254211426,
 'Kendrick Nunn': 87.73473358154297,
 'LeBron James': 1.9515291452407837,
 'Lonnie Walker IV': 29.177108764648438,
 'Matt Ryan': 27.828468322753906,
 'Max Christie': 13.685097694396973,
 'Patrick Beverley': 2.987292766571045,
 'Russell Westbrook': 1.0200003385543823,
 'Scotty Pippen Jr.': 49.392120361328125,
 'Thomas Bryant': 13.161378860473633,
 'Wenyen Gabriel': 18.043560028076172}