In [78]:
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.linear_model import LinearRegression
import os
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import LSTM
import datetime
from numpy import hstack

In [4]:
import tensorflow

In [41]:
#obtain list of dates
directory = "Boston Celtics"
list_dates = []
for filename in os.listdir(directory):
    if filename.endswith(".csv"):
        list_dates.append(filename)

In [42]:
# create dictionary 
final_data = {}

In [43]:
opponents = {}
# reads in each csv
for i in list_dates:
    data = pd.read_csv(f"Boston Celtics/{i}", index_col=0)
    #gathers data and adds to dict
    date = data["Date"].tolist()[0]
    
    opponents[date] = data["Opponent"][0]
    
    data[date] = data["Score"]
    final_data[date] = data[date]
    final_data[date].append

In [44]:
# convert dict to dataframe
data_df = pd.DataFrame(final_data)
data_df

06/16/2022  06/02/2022  06/10/2022  06/05/2022  \
Aaron Nesmith              0.00        0.00         NaN       11.50   
Al Horford                46.00       42.00       24.00       14.50   
Daniel Theis                NaN        5.50         NaN        9.25   
Derrick White              5.75       28.25       20.75       25.50   
Grant Williams             7.25        8.25        4.75       11.25   
Jaylen Brown              49.25       45.25       33.50       29.50   
Jayson Tatum              33.25       39.25       52.75       43.00   
Juwan Morgan               0.00        0.00         NaN         NaN   
Luke Kornet                0.75         NaN         NaN        3.50   
Malik Fitts                 NaN        0.00         NaN        3.50   
Marcus Smart              33.00       36.25       39.00       11.50   
Nik Stauskas               0.00        0.00         NaN        8.75   
Payton Pritchard           2.25       19.50        1.75       13.50   
Robert Williams III       30.75       24.50       34.00       10.00   
Sam Hauser                 0.00        0.00         NaN        5.00   

                     06/13/2022  04/17/2022  05/25/2022  05/19/2022  \
Aaron Nesmith              4.25         NaN        0.00        1.25   
Al Horford                21.75       44.25       38.25       21.75   
Daniel Theis                NaN       13.00         NaN        4.75   
Derrick White              8.75       22.25       27.25         NaN   
Grant Williams            11.25       13.00       12.50       27.00   
Jaylen Brown              34.75       45.25       36.00       40.00   
Jayson Tatum              46.00       53.00       49.00       43.25   
Juwan Morgan               1.25         NaN        0.00        2.25   
Luke Kornet                4.75         NaN        0.00        4.50   
Malik Fitts                 NaN         NaN        0.00         NaN   
Marcus Smart              26.25       42.25       17.25       63.25   
Nik Stauskas               0.00         NaN        0.00        7.75   
Payton Pritchard           0.75        4.75        1.25       18.50   
Robert Williams III       23.00         NaN       26.50       17.50   
Sam Hauser                 1.50         NaN         NaN         NaN   

                     05/27/2022  05/23/2022  ...  05/13/2022  05/17/2022  \
Aaron Nesmith              0.00       10.25  ...        1.25        8.75   
Al Horford                20.75       34.25  ...       28.50         NaN   
Daniel Theis                NaN        7.75  ...        6.50       18.00   
Derrick White             43.25       39.00  ...       22.75       10.00   
Grant Williams             6.50       16.25  ...       13.25       12.75   
Jaylen Brown              37.50       23.75  ...       37.25       44.00   
Jayson Tatum              51.75       51.50  ...       66.75       55.50   
Juwan Morgan                NaN        0.00  ...         NaN         NaN   
Luke Kornet                 NaN         NaN  ...         NaN         NaN   
Malik Fitts                 NaN        0.00  ...         NaN         NaN   
Marcus Smart              25.00         NaN  ...       40.25         NaN   
Nik Stauskas                NaN        2.00  ...        2.00         NaN   
Payton Pritchard           0.00       26.00  ...        3.50       33.75   
Robert Williams III       18.75       27.25  ...         NaN       34.25   
Sam Hauser                  NaN         NaN  ...         NaN         NaN   

                     05/03/2022  05/29/2022  05/15/2022  05/01/2022  \
Aaron Nesmith              1.25         NaN        4.75        2.75   
Al Horford                39.25       33.50       29.50       36.00   
Daniel Theis                NaN         NaN        9.75        6.00   
Derrick White             13.50       14.75        9.50       16.50   
Grant Williams            33.25       19.50       41.50       16.00   
Jaylen Brown              54.50       39.00       33.00       31.25   
Jayson Tatum              53.25  

In [45]:
tester.to_csv("Final_Score/Tables/Boston_Celtics.csv")

In [46]:
opp = pd.DataFrame.transpose(pd.DataFrame.from_dict(opponents, orient="index"))
data_df = data_df.append(opp)

/var/folders/g3/164q6cz52jv0sjllnsg7jdsm0000gn/T/ipykernel_28858/1654206437.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data_df = data_df.append(opp)


In [47]:

data_df

06/16/2022             06/02/2022  \
Aaron Nesmith                          0.0                    0.0   
Al Horford                            46.0                   42.0   
Daniel Theis                           NaN                    5.5   
Derrick White                         5.75                  28.25   
Grant Williams                        7.25                   8.25   
Jaylen Brown                         49.25                  45.25   
Jayson Tatum                         33.25                  39.25   
Juwan Morgan                           0.0                    0.0   
Luke Kornet                           0.75                    NaN   
Malik Fitts                            NaN                    0.0   
Marcus Smart                          33.0                  36.25   
Nik Stauskas                           0.0                    0.0   
Payton Pritchard                      2.25                   19.5   
Robert Williams III                  30.75                   24.5   
Sam Hauser                             0.0                    0.0   
0                    Golden State Warriors  Golden State Warriors   

                                06/10/2022             06/05/2022  \
Aaron Nesmith                          NaN                   11.5   
Al Horford                            24.0                   14.5   
Daniel Theis                           NaN                   9.25   
Derrick White                        20.75                   25.5   
Grant Williams                        4.75                  11.25   
Jaylen Brown                          33.5                   29.5   
Jayson Tatum                         52.75                   43.0   
Juwan Morgan                           NaN                    NaN   
Luke Kornet                            NaN                    3.5   
Malik Fitts                            NaN                    3.5   
Marcus Smart                          39.0                   11.5   
Nik Stauskas                           NaN                   8.75   
Payton Pritchard                      1.75                   13.5   
Robert Williams III                   34.0                   10.0   
Sam Hauser                             NaN                    5.0   
0                    Golden State Warriors  Golden State Warriors   

                                06/13/2022     04/17/2022  05/25/2022  \
Aaron Nesmith                         4.25            NaN         0.0   
Al Horford                           21.75          44.25       38.25   
Daniel Theis                           NaN           13.0         NaN   
Derrick White                         8.75          22.25       27.25   
Grant Williams                       11.25           13.0        12.5   
Jaylen Brown                         34.75          45.25        36.0   
Jayson Tatum                          46.0           53.0        49.0   
Juwan Morgan                          1.25            NaN         0.0   
Luke Kornet                           4.75            NaN         0.0   
Malik Fitts                            NaN            NaN         0.0   
Marcus Smart                         26.25          42.25       17.25   
Nik Stauskas                           0.0            NaN         0.0   
Payton Pritchard                      0.75           4.75        1.25   
Robert Williams III                   23.0            NaN        26.5   
Sam Hauser                             1.5            NaN         NaN   
0                    Golden State Warriors  Brooklyn Nets  Miami Heat   

                     05/19/2022  05/27/2022  05/23/2022  ...       05/13/2022  \
Aaron Nesmith              1.25         0.0       10.25  ...             1.25   
Al Horford                21.75       20.75       34.25  ...             28.5   
Daniel Theis               4.75         NaN        7.75  ...              6.5   
Derrick White               NaN       43.25        39.0  ...            22.75   
Grant Williams             27.0      

In [49]:
tester["Datetime"] = pd.to_datetime(data_df.columns.tolist()).tolist()

In [51]:
tester = pd.DataFrame.transpose(data_df)

In [15]:
#create dict
final_result = {}

In [52]:
tester

Aaron Nesmith Al Horford Daniel Theis Derrick White Grant Williams  \
06/16/2022           0.0       46.0          NaN          5.75           7.25   
06/02/2022           0.0       42.0          5.5         28.25           8.25   
06/10/2022           NaN       24.0          NaN         20.75           4.75   
06/05/2022          11.5       14.5         9.25          25.5          11.25   
06/13/2022          4.25      21.75          NaN          8.75          11.25   
04/17/2022           NaN      44.25         13.0         22.25           13.0   
05/25/2022           0.0      38.25          NaN         27.25           12.5   
05/19/2022          1.25      21.75         4.75           NaN           27.0   
05/27/2022           0.0      20.75          NaN         43.25            6.5   
05/23/2022         10.25      34.25         7.75          39.0          16.25   
05/21/2022           0.0       48.0         5.25           8.0          20.75   
05/09/2022           NaN       48.5         2.25          23.0           13.5   
05/11/2022           NaN       34.5        14.75         28.25            3.0   
05/07/2022           NaN       55.5         0.75          19.5           25.5   
05/13/2022          1.25       28.5          6.5         22.75          13.25   
05/17/2022          8.75        NaN         18.0          10.0          12.75   
05/03/2022          1.25      39.25          NaN          13.5          33.25   
05/29/2022           NaN       33.5          NaN         14.75           19.5   
05/15/2022          4.75       29.5         9.75           9.5           41.5   
05/01/2022          2.75       36.0          6.0          16.5           16.0   
06/08/2022          1.25       34.5          NaN         14.75          18.25   
04/25/2022           NaN       23.0         20.5          19.5          26.75   
04/20/2022           NaN       34.0         26.5          8.25           30.0   
04/23/2022           NaN      15.25         20.0          12.5          16.75   

           Jaylen Brown Jayson Tatum Juwan Morgan Luke Kornet Malik Fitts  \
06/16/2022        49.25        33.25          0.0        0.75         NaN   
06/02/2022        45.25        39.25          0.0         NaN         0.0   
06/10/2022         33.5        52.75          NaN         NaN         NaN   
06/05/2022         29.5         43.0          NaN         3.5         3.5   
06/13/2022        34.75         46.0         1.25        4.75         NaN   
04/17/2022        45.25         53.0          NaN         NaN         NaN   
05/25/2022         36.0         49.0          0.0         0.0         0.0   
05/19/2022         40.0        43.25         2.25         4.5         NaN   
05/27/2022         37.5        51.75          NaN         NaN         NaN   
05/23/2022        23.75         51.5          0.0         NaN         0.0   
05/21/2022        54.75         21.0         1.25         0.0         0.0   
05/09/2022        25.25        54.25          NaN         NaN         NaN   
05/11/2022         47.5         52.0          NaN         NaN         NaN   
05/07/2022         48.5        24.25          NaN         NaN         NaN   
05/13/2022        37.25        66.75          NaN         NaN         NaN   
05/17/2022         44.0         55.5          NaN         NaN         NaN   
05/03/2022         54.5        53.25          NaN        1.25        1.25   
05/29/2022         39.0         54.5          NaN         NaN         NaN   
05/15/2022         33.0         43.5          0.0         0.0         3.5   
05/01/2022        31.25         42.0          NaN         0.0        3.25   
06/08/2022        48.75         49.5          0.0         NaN         0.0   
04/25/2022         38.0        39.25          NaN         NaN         NaN   
04/20/2022         41.0         43.0          NaN         NaN         NaN   
04/23/2022         38.5        65.25          NaN         NaN         NaN   

           Marcus Smart Nik Stauskas Payton Pritchard Rober

In [30]:
columns = tester.columns.tolist()[:-2]

In [31]:
columns

['Aaron Nesmith',
 'Al Horford',
 'Daniel Theis',
 'Derrick White',
 'Grant Williams',
 'Jaylen Brown',
 'Jayson Tatum',
 'Juwan Morgan',
 'Luke Kornet',
 'Malik Fitts',
 'Marcus Smart',
 'Nik Stauskas',
 'Payton Pritchard',
 'Robert Williams III',
 'Sam Hauser']

In [37]:
tester

Aaron Nesmith Al Horford Daniel Theis Derrick White Grant Williams  \
06/16/2022           0.0       46.0          NaN          5.75           7.25   
06/02/2022           0.0       42.0          5.5         28.25           8.25   
06/10/2022           NaN       24.0          NaN         20.75           4.75   
06/05/2022          11.5       14.5         9.25          25.5          11.25   
06/13/2022          4.25      21.75          NaN          8.75          11.25   
04/17/2022           NaN      44.25         13.0         22.25           13.0   
05/25/2022           0.0      38.25          NaN         27.25           12.5   
05/19/2022          1.25      21.75         4.75           NaN           27.0   
05/27/2022           0.0      20.75          NaN         43.25            6.5   
05/23/2022         10.25      34.25         7.75          39.0          16.25   
05/21/2022           0.0       48.0         5.25           8.0          20.75   
05/09/2022           NaN       48.5         2.25          23.0           13.5   
05/11/2022           NaN       34.5        14.75         28.25            3.0   
05/07/2022           NaN       55.5         0.75          19.5           25.5   
05/13/2022          1.25       28.5          6.5         22.75          13.25   
05/17/2022          8.75        NaN         18.0          10.0          12.75   
05/03/2022          1.25      39.25          NaN          13.5          33.25   
05/29/2022           NaN       33.5          NaN         14.75           19.5   
05/15/2022          4.75       29.5         9.75           9.5           41.5   
05/01/2022          2.75       36.0          6.0          16.5           16.0   
06/08/2022          1.25       34.5          NaN         14.75          18.25   
04/25/2022           NaN       23.0         20.5          19.5          26.75   
04/20/2022           NaN       34.0         26.5          8.25           30.0   
04/23/2022           NaN      15.25         20.0          12.5          16.75   

           Jaylen Brown Jayson Tatum Juwan Morgan Luke Kornet Malik Fitts  \
06/16/2022        49.25        33.25          0.0        0.75         NaN   
06/02/2022        45.25        39.25          0.0         NaN         0.0   
06/10/2022         33.5        52.75          NaN         NaN         NaN   
06/05/2022         29.5         43.0          NaN         3.5         3.5   
06/13/2022        34.75         46.0         1.25        4.75         NaN   
04/17/2022        45.25         53.0          NaN         NaN         NaN   
05/25/2022         36.0         49.0          0.0         0.0         0.0   
05/19/2022         40.0        43.25         2.25         4.5         NaN   
05/27/2022         37.5        51.75          NaN         NaN         NaN   
05/23/2022        23.75         51.5          0.0         NaN         0.0   
05/21/2022        54.75         21.0         1.25         0.0         0.0   
05/09/2022        25.25        54.25          NaN         NaN         NaN   
05/11/2022         47.5         52.0          NaN         NaN         NaN   
05/07/2022         48.5        24.25          NaN         NaN         NaN   
05/13/2022        37.25        66.75          NaN         NaN         NaN   
05/17/2022         44.0         55.5          NaN         NaN         NaN   
05/03/2022         54.5        53.25          NaN        1.25        1.25   
05/29/2022         39.0         54.5          NaN         NaN         NaN   
05/15/2022         33.0         43.5          0.0         0.0         3.5   
05/01/2022        31.25         42.0          NaN         0.0        3.25   
06/08/2022        48.75         49.5          0.0         NaN         0.0   
04/25/2022         38.0        39.25          NaN         NaN         NaN   
04/20/2022         41.0         43.0          NaN         NaN         NaN   
04/23/2022         38.5        65.25          NaN         NaN         NaN   

           Marcus Smart Nik Stauskas Payton Pritchard Rober

In [32]:
add = {}

#iterate through index
for column in columns:
    print(column)
    
# univariate data prep LSTM
    from numpy import array

    # split sequence
    def split_sequence(sequence, n_steps):
        X, y = list(), list()
        for i in range(len(sequence)):
            # find end of pattern 
            end_ix = i + n_steps
            #check if beyond sequence to break
            if end_ix > len(sequence)-1:
                break
            #gather input and output parts of the pattern
            seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
            X.append(seq_x)
            y.append(seq_y)
        return array(X), array(y)
    # sequence 
    rent_rate = list(tester[column].dropna())
    # number of steps
    n_steps = 3
    if len(rent_rate) < 5:
        continue
    X, y = split_sequence(rent_rate, n_steps)
    # summarize the data
    for i in range(len(X)):
        print(X[i], y[i])

    # reshape from [samples, timesteps] into [samples, timesteps, features]
    n_features = 1
    X = X.reshape((X.shape[0], X.shape[1], n_features))

    model = Sequential()
    model.add(LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
    model.add(Dense(1))
    model.compile(optimizer='adam', loss='mse')

    # fit model
    model.fit(X, y, epochs=200, verbose=0)

    # demonstrate prediction
    x_input = array(rent_rate[-3:])
    x_input = x_input.reshape((1, n_steps, n_features))
    yhat = model.predict(x_input, verbose=0)
    add[column] = yhat.tolist()[0][0]

Aaron Nesmith
[ 0.   0.  11.5] 4.25
[ 0.   11.5   4.25] 0.0
[11.5   4.25  0.  ] 1.25
[4.25 0.   1.25] 0.0
[0.   1.25 0.  ] 10.25
[ 1.25  0.   10.25] 0.0
[ 0.   10.25  0.  ] 1.25
[10.25  0.    1.25] 8.75
[0.   1.25 8.75] 1.25
[1.25 8.75 1.25] 4.75
[8.75 1.25 4.75] 2.75
[1.25 4.75 2.75] 1.25


2022-09-10 19:08:12.765467: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Al Horford
[46. 42. 24.] 14.5
[42.  24.  14.5] 21.75
[24.   14.5  21.75] 44.25
[14.5  21.75 44.25] 38.25
[21.75 44.25 38.25] 21.75
[44.25 38.25 21.75] 20.75
[38.25 21.75 20.75] 34.25
[21.75 20.75 34.25] 48.0
[20.75 34.25 48.  ] 48.5
[34.25 48.   48.5 ] 34.5
[48.  48.5 34.5] 55.5
[48.5 34.5 55.5] 28.5
[34.5 55.5 28.5] 39.25
[55.5  28.5  39.25] 33.5
[28.5  39.25 33.5 ] 29.5
[39.25 33.5  29.5 ] 36.0
[33.5 29.5 36. ] 34.5
[29.5 36.  34.5] 23.0
[36.  34.5 23. ] 34.0
[34.5 23.  34. ] 15.25


2022-09-10 19:08:16.052973: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 19:08:16.452662: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Daniel Theis
[ 5.5   9.25 13.  ] 4.75
[ 9.25 13.    4.75] 7.75
[13.    4.75  7.75] 5.25
[4.75 7.75 5.25] 2.25
[7.75 5.25 2.25] 14.75
[ 5.25  2.25 14.75] 0.75
[ 2.25 14.75  0.75] 6.5
[14.75  0.75  6.5 ] 18.0
[ 0.75  6.5  18.  ] 9.75
[ 6.5  18.    9.75] 6.0
[18.    9.75  6.  ] 20.5
[ 9.75  6.   20.5 ] 26.5
[ 6.  20.5 26.5] 20.0


2022-09-10 19:08:19.712264: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 19:08:20.113776: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Derrick White
[ 5.75 28.25 20.75] 25.5
[28.25 20.75 25.5 ] 8.75
[20.75 25.5   8.75] 22.25
[25.5   8.75 22.25] 27.25
[ 8.75 22.25 27.25] 43.25
[22.25 27.25 43.25] 39.0
[27.25 43.25 39.  ] 8.0
[43.25 39.    8.  ] 23.0
[39.  8. 23.] 28.25
[ 8.   23.   28.25] 19.5
[23.   28.25 19.5 ] 22.75
[28.25 19.5  22.75] 10.0
[19.5  22.75 10.  ] 13.5
[22.75 10.   13.5 ] 14.75
[10.   13.5  14.75] 9.5
[13.5  14.75  9.5 ] 16.5
[14.75  9.5  16.5 ] 14.75
[ 9.5  16.5  14.75] 19.5
[16.5  14.75 19.5 ] 8.25
[14.75 19.5   8.25] 12.5


2022-09-10 19:08:23.360453: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 19:08:23.902167: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Grant Williams
[7.25 8.25 4.75] 11.25
[ 8.25  4.75 11.25] 11.25
[ 4.75 11.25 11.25] 13.0
[11.25 11.25 13.  ] 12.5
[11.25 13.   12.5 ] 27.0
[13.  12.5 27. ] 6.5
[12.5 27.   6.5] 16.25
[27.    6.5  16.25] 20.75
[ 6.5  16.25 20.75] 13.5
[16.25 20.75 13.5 ] 3.0
[20.75 13.5   3.  ] 25.5
[13.5  3.  25.5] 13.25
[ 3.   25.5  13.25] 12.75
[25.5  13.25 12.75] 33.25
[13.25 12.75 33.25] 19.5
[12.75 33.25 19.5 ] 41.5
[33.25 19.5  41.5 ] 16.0
[19.5 41.5 16. ] 18.25
[41.5  16.   18.25] 26.75
[16.   18.25 26.75] 30.0
[18.25 26.75 30.  ] 16.75


2022-09-10 19:08:27.160412: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 19:08:27.564811: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Jaylen Brown
[49.25 45.25 33.5 ] 29.5
[45.25 33.5  29.5 ] 34.75
[33.5  29.5  34.75] 45.25
[29.5  34.75 45.25] 36.0
[34.75 45.25 36.  ] 40.0
[45.25 36.   40.  ] 37.5
[36.  40.  37.5] 23.75
[40.   37.5  23.75] 54.75
[37.5  23.75 54.75] 25.25
[23.75 54.75 25.25] 47.5
[54.75 25.25 47.5 ] 48.5
[25.25 47.5  48.5 ] 37.25
[47.5  48.5  37.25] 44.0
[48.5  37.25 44.  ] 54.5
[37.25 44.   54.5 ] 39.0
[44.  54.5 39. ] 33.0
[54.5 39.  33. ] 31.25
[39.   33.   31.25] 48.75
[33.   31.25 48.75] 38.0
[31.25 48.75 38.  ] 41.0
[48.75 38.   41.  ] 38.5


2022-09-10 19:08:30.839285: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 19:08:31.239834: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Jayson Tatum
[33.25 39.25 52.75] 43.0
[39.25 52.75 43.  ] 46.0
[52.75 43.   46.  ] 53.0
[43. 46. 53.] 49.0
[46. 53. 49.] 43.25
[53.   49.   43.25] 51.75
[49.   43.25 51.75] 51.5
[43.25 51.75 51.5 ] 21.0
[51.75 51.5  21.  ] 54.25
[51.5  21.   54.25] 52.0
[21.   54.25 52.  ] 24.25
[54.25 52.   24.25] 66.75
[52.   24.25 66.75] 55.5
[24.25 66.75 55.5 ] 53.25
[66.75 55.5  53.25] 54.5
[55.5  53.25 54.5 ] 43.5
[53.25 54.5  43.5 ] 42.0
[54.5 43.5 42. ] 49.5
[43.5 42.  49.5] 39.25
[42.   49.5  39.25] 43.0
[49.5  39.25 43.  ] 65.25


2022-09-10 19:08:34.493859: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 19:08:35.036575: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Juwan Morgan
[0.   0.   1.25] 0.0
[0.   1.25 0.  ] 2.25
[1.25 0.   2.25] 0.0
[0.   2.25 0.  ] 1.25
[2.25 0.   1.25] 0.0
[0.   1.25 0.  ] 0.0


2022-09-10 19:08:38.292390: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 19:08:38.690511: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Luke Kornet
[0.75 3.5  4.75] 0.0
[3.5  4.75 0.  ] 4.5
[4.75 0.   4.5 ] 0.0
[0.  4.5 0. ] 1.25
[4.5  0.   1.25] 0.0
[0.   1.25 0.  ] 0.0


2022-09-10 19:08:41.910450: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 19:08:42.310269: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Malik Fitts
[0.  3.5 0. ] 0.0
[3.5 0.  0. ] 0.0
[0. 0. 0.] 1.25
[0.   0.   1.25] 3.5
[0.   1.25 3.5 ] 3.25
[1.25 3.5  3.25] 0.0


2022-09-10 19:08:45.547106: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 19:08:46.086626: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Marcus Smart
[33.   36.25 39.  ] 11.5
[36.25 39.   11.5 ] 26.25
[39.   11.5  26.25] 42.25
[11.5  26.25 42.25] 17.25
[26.25 42.25 17.25] 63.25
[42.25 17.25 63.25] 25.0
[17.25 63.25 25.  ] 30.0
[63.25 25.   30.  ] 36.0
[25. 30. 36.] 27.5
[30.  36.  27.5] 15.5
[36.  27.5 15.5] 40.25
[27.5  15.5  40.25] 47.75
[15.5  40.25 47.75] 38.25
[40.25 47.75 38.25] 23.25
[47.75 38.25 23.25] 39.25
[38.25 23.25 39.25] 43.75
[23.25 39.25 43.75] 21.25
[39.25 43.75 21.25] 30.75


2022-09-10 19:08:49.309770: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 19:08:49.712691: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Nik Stauskas
[0.   0.   8.75] 0.0
[0.   8.75 0.  ] 0.0
[8.75 0.   0.  ] 7.75
[0.   0.   7.75] 2.0
[0.   7.75 2.  ] 3.5
[7.75 2.   3.5 ] 2.0
[2.  3.5 2. ] 0.0
[3.5 2.  0. ] 1.5
[2.  0.  1.5] 0.0
[0.  1.5 0. ] 0.0


2022-09-10 19:08:52.972471: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 19:08:53.372907: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Payton Pritchard
[ 2.25 19.5   1.75] 13.5
[19.5   1.75 13.5 ] 0.75
[ 1.75 13.5   0.75] 4.75
[13.5   0.75  4.75] 1.25
[0.75 4.75 1.25] 18.5
[ 4.75  1.25 18.5 ] 0.0
[ 1.25 18.5   0.  ] 26.0
[18.5  0.  26. ] 9.5
[ 0.  26.   9.5] 11.75
[26.    9.5  11.75] 8.0
[ 9.5  11.75  8.  ] 7.0
[11.75  8.    7.  ] 3.5
[8.  7.  3.5] 33.75
[ 7.    3.5  33.75] 14.75
[ 3.5  33.75 14.75] 0.0
[33.75 14.75  0.  ] 26.75
[14.75  0.   26.75] 9.5
[ 0.   26.75  9.5 ] 4.5
[26.75  9.5   4.5 ] 4.25
[9.5  4.5  4.25] 16.0
[ 4.5   4.25 16.  ] 14.5


2022-09-10 19:08:56.635120: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 19:08:57.178524: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Robert Williams III
[30.75 24.5  34.  ] 10.0
[24.5 34.  10. ] 23.0
[34. 10. 23.] 26.5
[10.  23.  26.5] 17.5
[23.  26.5 17.5] 18.75
[26.5  17.5  18.75] 27.25
[17.5  18.75 27.25] 32.25
[18.75 27.25 32.25] 34.25
[27.25 32.25 34.25] 20.0
[32.25 34.25 20.  ] 6.75
[34.25 20.    6.75] 24.0
[20.    6.75 24.  ] 34.5
[ 6.75 24.   34.5 ] 10.75
[24.   34.5  10.75] 8.0


2022-09-10 19:09:00.426105: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 19:09:00.825602: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Sam Hauser
[0. 0. 5.] 1.5
[0.  5.  1.5] 3.25
[5.   1.5  3.25] 0.0
[1.5  3.25 0.  ] 0.0


2022-09-10 19:09:04.102607: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 19:09:04.504594: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 19:09:07.764643: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


In [36]:
add

{'Aaron Nesmith': 1.2299470901489258,
 'Al Horford': 45.19719314575195,
 'Daniel Theis': 18.94312286376953,
 'Derrick White': 14.147613525390625,
 'Grant Williams': 21.407642364501953,
 'Jaylen Brown': 37.724205017089844,
 'Jayson Tatum': 44.377384185791016,
 'Juwan Morgan': 0.6993505954742432,
 'Luke Kornet': 0.019753864035010338,
 'Malik Fitts': -2.499878168106079,
 'Marcus Smart': 54.04118728637695,
 'Nik Stauskas': 0.4328417181968689,
 'Payton Pritchard': 2.787205696105957,
 'Robert Williams III': 30.404296875,
 'Sam Hauser': -0.32293668389320374}

In [34]:
# convert dict to dataframe
Data = pd.DataFrame.from_dict(add, orient='index')

In [35]:
Data

0
Aaron Nesmith         1.229947
Al Horford           45.197193
Daniel Theis         18.943123
Derrick White        14.147614
Grant Williams       21.407642
Jaylen Brown         37.724205
Jayson Tatum         44.377384
Juwan Morgan          0.699351
Luke Kornet           0.019754
Malik Fitts          -2.499878
Marcus Smart         54.041187
Nik Stauskas          0.432842
Payton Pritchard      2.787206
Robert Williams III  30.404297
Sam Hauser           -0.322937

In [ ]:
# convert dataframe to csv
mypath = "Final_Score/LSTM"
if not os.path.isdir(mypath):
    os.makedirs(mypath)
Data.to_csv(f"{mypath}/BostonCeltics.csv", index=True)

Function below used for multiple teams

In [ ]:
#obtain list of dates
directorys = ["Boston Celtics"]


for directory in directorys:
    list_dates = []
    for filename in os.listdir(directory):
        if filename.endswith(".csv"):
            list_dates.append(filename)
    # create dictionary 
    final_data = {}
    
    # reads in each csv
    for i in list_dates:
        data = pd.read_csv(f"{directory}/{i}", index_col=0)

        #gathers data and adds to dict
        date = data["Date"].tolist()[0]
        data[date] = data["Score"]
        final_data[date] = data[date]
    # convert dict to dataframe
    data_df = pd.DataFrame(final_data)
    
    
    tester = pd.DataFrame.transpose(data_df)
    columns = tester.columns.tolist()
    
    #create dict
    final_result = {}
    
    add = {}

    #iterate through index
    for column in columns:
        print(column)

    # univariate data prep LSTM
        from numpy import array

        # split sequence
        def split_sequence(sequence, n_steps):
            X, y = list(), list()
            for i in range(len(sequence)):
                # find end of pattern 
                end_ix = i + n_steps
                #check if beyond sequence to break
                if end_ix > len(sequence)-1:
                    break
                #gather input and output parts of the pattern
                seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
                X.append(seq_x)
                y.append(seq_y)
            return array(X), array(y)
        # sequence 
        rent_rate = list(tester[column].dropna())
        # number of steps
        n_steps = 3
        if len(rent_rate) < 6:
            continue
        X, y = split_sequence(rent_rate, n_steps)
        # summarize the data
        for i in range(len(X)):
            print(X[i], y[i])

        # reshape from [samples, timesteps] into [samples, timesteps, features]
        n_features = 1
        X = X.reshape((X.shape[0], X.shape[1], n_features))

        model = Sequential()
        model.add(LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
        model.add(Dense(1))
        model.compile(optimizer='adam', loss='mse')

        # fit model
        model.fit(X, y, epochs=200, verbose=0)

        # demonstrate prediction
        x_input = array(rent_rate[-3:])
        x_input = x_input.reshape((1, n_steps, n_features))
        yhat = model.predict(x_input, verbose=0)
        add[column] = yhat.tolist()[0][0]
    # convert dict to dataframe
    Data = pd.DataFrame.from_dict(add, orient='index')

    
    # convert dataframe to csv
    mypath = f"Final_Score/LSTM/{directory}"
    if not os.path.isdir(mypath):
        os.makedirs(mypath)
    Data.to_csv(f"{mypath}/{directory}.csv", index=True)

Backtesting

In [12]:
list_dates

['06-16.csv',
 '06-02.csv',
 '06-10.csv',
 '06-05.csv',
 '06-13.csv',
 '04-17.csv',
 '05-25.csv',
 '05-19.csv',
 '05-27.csv',
 '05-23.csv',
 '05-21.csv',
 '05-09.csv',
 '05-11.csv',
 '05-07.csv',
 '05-13.csv',
 '05-17.csv',
 '05-03.csv',
 '05-29.csv',
 '05-15.csv',
 '05-01.csv',
 '06-08.csv',
 '04-25.csv',
 '04-20.csv',
 '04-23.csv']

In [13]:
collect = []
for name in opponents:
    if opponents[name] not in collect:
        collect.append(opponents[name])

In [14]:
collect

['Golden State Warriors', 'Brooklyn Nets', 'Miami Heat', 'Milwaukee Bucks']

In [15]:
data_df

06/16/2022  06/02/2022  06/10/2022  06/05/2022  \
Aaron Nesmith              0.00        0.00         NaN       11.50   
Al Horford                46.00       42.00       24.00       14.50   
Daniel Theis                NaN        5.50         NaN        9.25   
Derrick White              5.75       28.25       20.75       25.50   
Grant Williams             7.25        8.25        4.75       11.25   
Jaylen Brown              49.25       45.25       33.50       29.50   
Jayson Tatum              33.25       39.25       52.75       43.00   
Juwan Morgan               0.00        0.00         NaN         NaN   
Luke Kornet                0.75         NaN         NaN        3.50   
Malik Fitts                 NaN        0.00         NaN        3.50   
Marcus Smart              33.00       36.25       39.00       11.50   
Nik Stauskas               0.00        0.00         NaN        8.75   
Payton Pritchard           2.25       19.50        1.75       13.50   
Robert Williams III       30.75       24.50       34.00       10.00   
Sam Hauser                 0.00        0.00         NaN        5.00   

                     06/13/2022  04/17/2022  05/25/2022  05/19/2022  \
Aaron Nesmith              4.25         NaN        0.00        1.25   
Al Horford                21.75       44.25       38.25       21.75   
Daniel Theis                NaN       13.00         NaN        4.75   
Derrick White              8.75       22.25       27.25         NaN   
Grant Williams            11.25       13.00       12.50       27.00   
Jaylen Brown              34.75       45.25       36.00       40.00   
Jayson Tatum              46.00       53.00       49.00       43.25   
Juwan Morgan               1.25         NaN        0.00        2.25   
Luke Kornet                4.75         NaN        0.00        4.50   
Malik Fitts                 NaN         NaN        0.00         NaN   
Marcus Smart              26.25       42.25       17.25       63.25   
Nik Stauskas               0.00         NaN        0.00        7.75   
Payton Pritchard           0.75        4.75        1.25       18.50   
Robert Williams III       23.00         NaN       26.50       17.50   
Sam Hauser                 1.50         NaN         NaN         NaN   

                     05/27/2022  05/23/2022  ...  05/13/2022  05/17/2022  \
Aaron Nesmith              0.00       10.25  ...        1.25        8.75   
Al Horford                20.75       34.25  ...       28.50         NaN   
Daniel Theis                NaN        7.75  ...        6.50       18.00   
Derrick White             43.25       39.00  ...       22.75       10.00   
Grant Williams             6.50       16.25  ...       13.25       12.75   
Jaylen Brown              37.50       23.75  ...       37.25       44.00   
Jayson Tatum              51.75       51.50  ...       66.75       55.50   
Juwan Morgan                NaN        0.00  ...         NaN         NaN   
Luke Kornet                 NaN         NaN  ...         NaN         NaN   
Malik Fitts                 NaN        0.00  ...         NaN         NaN   
Marcus Smart              25.00         NaN  ...       40.25         NaN   
Nik Stauskas                NaN        2.00  ...        2.00         NaN   
Payton Pritchard           0.00       26.00  ...        3.50       33.75   
Robert Williams III       18.75       27.25  ...         NaN       34.25   
Sam Hauser                  NaN         NaN  ...         NaN         NaN   

                     05/03/2022  05/29/2022  05/15/2022  05/01/2022  \
Aaron Nesmith              1.25         NaN        4.75        2.75   
Al Horford                39.25       33.50       29.50       36.00   
Daniel Theis                NaN         NaN        9.75        6.00   
Derrick White             13.50       14.75        9.50       16.50   
Grant Williams            33.25       19.50       41.50       16.00   
Jaylen Brown              54.50       39.00       33.00       31.25   
Jayson Tatum              53.25  

In [16]:
directorys

NameError: name 'directorys' is not defined

In [27]:
#obtain list of dates
directorys = collect


for directory in directorys:
    print(directory)
    list_dates = []
    for filename in os.listdir(directory):
        if filename.endswith(".csv"):
            list_dates.append(filename)
    # create dictionary 
    final_data = {}
    
    # reads in each csv
    for i in list_dates:
        data = pd.read_csv(f"{directory}/{i}", index_col=0)

        #gathers data and adds to dict
        date = data["Date"].tolist()[0]
        data[date] = data["Score"]
        final_data[date] = data[date]
    # convert dict to dataframe
    opp = pd.DataFrame(final_data)
    
    
    opp_df = pd.DataFrame.transpose(opp)
    
    opp_df["Datetime"] = pd.to_datetime(opp.columns.tolist()).tolist()
    
    columns = opp_df.columns.tolist()[:-1]
    
    main_test = tester.columns.tolist()[:-2]
    
    for date in tester.loc[tester[0] == directory]["Datetime"]:
        print(date)
        main = tester.loc[tester["Datetime"] < date]
        results = opp_df.loc[opp_df["Datetime"] < date]
    
    
        #create dict
        final_result = {}

        add = {}

        #iterate through index
        for column in columns:
            print(column)

        # univariate data prep LSTM
            from numpy import array

            # split sequence
            def split_sequence(sequence, n_steps):
                X, y = list(), list()
                for i in range(len(sequence)):
                    # find end of pattern 
                    end_ix = i + n_steps
                    #check if beyond sequence to break
                    if end_ix > len(sequence)-1:
                        break
                    #gather input and output parts of the pattern
                    seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
                    X.append(seq_x)
                    y.append(seq_y)
                return array(X), array(y)
            # sequence 
            rent_rate = list(results[column].dropna())
            # number of steps
            n_steps = 5
            if len(rent_rate) < 5:
                continue
            X, y = split_sequence(rent_rate, n_steps)
            # summarize the data
            for i in range(len(X)):
                print(X[i], y[i])

            # reshape from [samples, timesteps] into [samples, timesteps, features]
            n_features = 1
            X = X.reshape((X.shape[0], X.shape[1], n_features))

            model = Sequential()
            model.add(LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
            model.add(Dense(1))
            model.compile(optimizer='adam', loss='mse')

            # fit model
            model.fit(X, y, epochs=200, verbose=0)

            # demonstrate prediction
            x_input = array(rent_rate[-5:])
            x_input = x_input.reshape((1, n_steps, n_features))
            yhat = model.predict(x_input, verbose=0)
            add[column] = yhat.tolist()[0][0]
        # convert dict to dataframe
        Data = pd.DataFrame.from_dict(add, orient='index')


        # convert dataframe to csv
        mypath = f"Final_Score/LSTM/Backtesting/{directory}"
        if not os.path.isdir(mypath):
            os.makedirs(mypath)
        Data.to_csv(f"{mypath}/{directory}_{date}.csv", index=True)
        
        #create dict
        final_result = {}

        add = {}

        
        #iterate through index
        for column in main_test:
            print(column)

        # univariate data prep LSTM
            from numpy import array

            # split sequence
            def split_sequence(sequence, n_steps):
                X, y = list(), list()
                for i in range(len(sequence)):
                    # find end of pattern 
                    end_ix = i + n_steps
                    #check if beyond sequence to break
                    if end_ix > len(sequence)-1:
                        break
                    #gather input and output parts of the pattern
                    seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
                    X.append(seq_x)
                    y.append(seq_y)
                return array(X), array(y)
            # sequence 
            rent_rate = list(main[column].dropna())
            # number of steps
            n_steps = 5
            if len(rent_rate) < 5:
                continue
            X, y = split_sequence(rent_rate, n_steps)
            # summarize the data
            for i in range(len(X)):
                print(X[i], y[i])

            # reshape from [samples, timesteps] into [samples, timesteps, features]
            n_features = 1
            X = X.reshape((X.shape[0], X.shape[1], n_features))

            model = Sequential()
            model.add(LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
            model.add(Dense(1))
            model.compile(optimizer='adam', loss='mse')

            # fit model
            model.fit(X, y, epochs=200, verbose=0)

            # demonstrate prediction
            x_input = array(rent_rate[-5:])
            x_input = x_input.reshape((1, n_steps, n_features))
            yhat = model.predict(x_input, verbose=0)
            add[column] = yhat.tolist()[0][0]
        # convert dict to dataframe
        Data = pd.DataFrame.from_dict(add, orient='index')


        # convert dataframe to csv
        mypath = f"Final_Score/LSTM/Backtesting/Boston"
        if not os.path.isdir(mypath):
            os.makedirs(mypath)
        Data.to_csv(f"{mypath}/Boston_{date}.csv", index=True)

Golden State Warriors
2022-06-16 00:00:00
Andre Iguodala
[11.5   3.   10.5   0.    0.25] 15.0
Andrew Wiggins
[34.75 42.   21.5  49.25 32.25] 34.25
[42.   21.5  49.25 32.25 34.25] 21.25
[21.5  49.25 32.25 34.25 21.25] 35.0
[49.25 32.25 34.25 21.25 35.  ] 45.75
[32.25 34.25 21.25 35.   45.75] 36.5
[34.25 21.25 35.   45.75 36.5 ] 34.75
[21.25 35.   45.75 36.5  34.75] 8.25
[35.   45.75 36.5  34.75  8.25] 29.25
[45.75 36.5  34.75  8.25 29.25] 40.25
[36.5  34.75  8.25 29.25 40.25] 33.25
[34.75  8.25 29.25 40.25 33.25] 28.5
[ 8.25 29.25 40.25 33.25 28.5 ] 22.75
[29.25 40.25 33.25 28.5  22.75] 36.75
[40.25 33.25 28.5  22.75 36.75] 30.5
[33.25 28.5  22.75 36.75 30.5 ] 37.0
[28.5  22.75 36.75 30.5  37.  ] 20.5
Damion Lee
[0.   0.   0.   4.5  9.25] 15.0
[ 0.    0.    4.5   9.25 15.  ] 0.0
[ 0.    4.5   9.25 15.    0.  ] 5.75
[ 4.5   9.25 15.    0.    5.75] 1.0
[ 9.25 15.    0.    5.75  1.  ] 14.25
[15.    0.    5.75  1.   14.25] 11.75
[ 0.    5.75  1.   14.25 11.75] 5.5
[ 5.75  1.   14.25 11.75  

Grant Williams
[ 8.25  4.75 11.25 11.25 13.  ] 12.5
[ 4.75 11.25 11.25 13.   12.5 ] 27.0
[11.25 11.25 13.   12.5  27.  ] 6.5
[11.25 13.   12.5  27.    6.5 ] 16.25
[13.   12.5  27.    6.5  16.25] 20.75
[12.5  27.    6.5  16.25 20.75] 13.5
[27.    6.5  16.25 20.75 13.5 ] 3.0
[ 6.5  16.25 20.75 13.5   3.  ] 25.5
[16.25 20.75 13.5   3.   25.5 ] 13.25
[20.75 13.5   3.   25.5  13.25] 12.75
[13.5   3.   25.5  13.25 12.75] 33.25
[ 3.   25.5  13.25 12.75 33.25] 19.5
[25.5  13.25 12.75 33.25 19.5 ] 41.5
[13.25 12.75 33.25 19.5  41.5 ] 16.0
[12.75 33.25 19.5  41.5  16.  ] 18.25
[33.25 19.5  41.5  16.   18.25] 26.75
[19.5  41.5  16.   18.25 26.75] 30.0
[41.5  16.   18.25 26.75 30.  ] 16.75
Jaylen Brown
[45.25 33.5  29.5  34.75 45.25] 36.0
[33.5  29.5  34.75 45.25 36.  ] 40.0
[29.5  34.75 45.25 36.   40.  ] 37.5
[34.75 45.25 36.   40.   37.5 ] 23.75
[45.25 36.   40.   37.5  23.75] 54.75
[36.   40.   37.5  23.75 54.75] 25.25
[40.   37.5  23.75 54.75 25.25] 47.5
[37.5  23.75 54.75 25.25 47.5 ] 48.5
[

Aaron Nesmith
[ 0.    1.25  0.   10.25  0.  ] 1.25
[ 1.25  0.   10.25  0.    1.25] 8.75
[ 0.   10.25  0.    1.25  8.75] 1.25
[10.25  0.    1.25  8.75  1.25] 4.75
[0.   1.25 8.75 1.25 4.75] 2.75
Al Horford
[44.25 38.25 21.75 20.75 34.25] 48.0
[38.25 21.75 20.75 34.25 48.  ] 48.5
[21.75 20.75 34.25 48.   48.5 ] 34.5
[20.75 34.25 48.   48.5  34.5 ] 55.5
[34.25 48.   48.5  34.5  55.5 ] 28.5
[48.  48.5 34.5 55.5 28.5] 39.25
[48.5  34.5  55.5  28.5  39.25] 33.5
[34.5  55.5  28.5  39.25 33.5 ] 29.5
[55.5  28.5  39.25 33.5  29.5 ] 36.0
[28.5  39.25 33.5  29.5  36.  ] 23.0
[39.25 33.5  29.5  36.   23.  ] 34.0
[33.5 29.5 36.  23.  34. ] 15.25
Daniel Theis
[13.    4.75  7.75  5.25  2.25] 14.75
[ 4.75  7.75  5.25  2.25 14.75] 0.75
[ 7.75  5.25  2.25 14.75  0.75] 6.5
[ 5.25  2.25 14.75  0.75  6.5 ] 18.0
[ 2.25 14.75  0.75  6.5  18.  ] 9.75
[14.75  0.75  6.5  18.    9.75] 6.0
[ 0.75  6.5  18.    9.75  6.  ] 20.5
[ 6.5  18.    9.75  6.   20.5 ] 26.5
[18.    9.75  6.   20.5  26.5 ] 20.0
Derrick White


IndexError: tuple index out of range

In [25]:
X

array([], dtype=float64)

## Backtest individual teams

In [ ]:
#obtain list of dates
directorys = ["Boston Celtics"]


for directory in directorys:
    list_dates = []
    for filename in os.listdir(directory):
        if filename.endswith(".csv"):
            list_dates.append(filename)
    # create dictionary 
    final_data = {}
    
    # reads in each csv
    for i in list_dates:
        data = pd.read_csv(f"{directory}/{i}", index_col=0)

        #gathers data and adds to dict
        date = data["Date"].tolist()[0]
        data[date] = data["Score"]
        final_data[date] = data[date]
    # convert dict to dataframe
    data_df = pd.DataFrame(final_data)
    
    
    tester = pd.DataFrame.transpose(data_df)
    columns = tester.columns.tolist()
    
    #create dict
    final_result = {}
    
    add = {}

    #iterate through index
    for column in columns:
        print(column)

    # univariate data prep LSTM
        from numpy import array

        # split sequence
        def split_sequence(sequence, n_steps):
            X, y = list(), list()
            for i in range(len(sequence)):
                # find end of pattern 
                end_ix = i + n_steps
                #check if beyond sequence to break
                if end_ix > len(sequence)-1:
                    break
                #gather input and output parts of the pattern
                seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
                X.append(seq_x)
                y.append(seq_y)
            return array(X), array(y)
        # sequence 
        rent_rate = list(tester[column].dropna())
        # number of steps
        n_steps = 3
        if len(rent_rate) < 5:
            continue
        X, y = split_sequence(rent_rate, n_steps)
        # summarize the data
        for i in range(len(X)):
            print(X[i], y[i])

        # reshape from [samples, timesteps] into [samples, timesteps, features]
        n_features = 1
        X = X.reshape((X.shape[0], X.shape[1], n_features))

        model = Sequential()
        model.add(LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
        model.add(Dense(1))
        model.compile(optimizer='adam', loss='mse')

        # fit model
        model.fit(X, y, epochs=200, verbose=0)

        # demonstrate prediction
        x_input = array(rent_rate[-3:])
        x_input = x_input.reshape((1, n_steps, n_features))
        yhat = model.predict(x_input, verbose=0)
        add[column] = yhat.tolist()[0][0]
    # convert dict to dataframe
    Data = pd.DataFrame.from_dict(add, orient='index')

    
    # convert dataframe to csv
    mypath = f"Final_Score/LSTM/{directory}"
    if not os.path.isdir(mypath):
        os.makedirs(mypath)
    Data.to_csv(f"{mypath}/{directory}.csv", index=True)

# Multiple Input Series

In [61]:
eff = pd.read_csv("Team_defensive_efficency.csv")

efficiency = {}

for name in opponents:
    team = opponents[name]
    team_name = team.split(" ")
    
    team_opp = team_name[0]
    
    if team_name[0] == ("Golden" or "New"):
        team_opp = f"{team_name[0]} {team_name[1]}"
    
    if team_name[0] == "Los":
        team_opp = f"LA {team_name[2]}"

    
    efficiency[name] = eff.loc[eff["Unnamed: 0"] == team_opp]["2021"].values[0]
    
eff_df = pd.DataFrame.transpose(pd.DataFrame.from_dict(efficiency, orient="index"))

eff_df.index = ["Efficiency"]

data_efficiency_df = data_df.append(eff_df)

data_efficiency_df.tail()

/var/folders/g3/164q6cz52jv0sjllnsg7jdsm0000gn/T/ipykernel_28858/1235662510.py:24: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data_efficiency_df = data_df.append(eff_df)


06/16/2022             06/02/2022  \
Payton Pritchard                      2.25                   19.5   
Robert Williams III                  30.75                   24.5   
Sam Hauser                             0.0                    0.0   
0                    Golden State Warriors  Golden State Warriors   
Efficiency                           1.042                  1.042   

                                06/10/2022             06/05/2022  \
Payton Pritchard                      1.75                   13.5   
Robert Williams III                   34.0                   10.0   
Sam Hauser                             NaN                    5.0   
0                    Golden State Warriors  Golden State Warriors   
Efficiency                           1.042                  1.042   

                                06/13/2022     04/17/2022  05/25/2022  \
Payton Pritchard                      0.75           4.75        1.25   
Robert Williams III                   23.0            NaN        26.5   
Sam Hauser                             1.5            NaN         NaN   
0                    Golden State Warriors  Brooklyn Nets  Miami Heat   
Efficiency                           1.042          1.093       1.052   

                     05/19/2022  05/27/2022  05/23/2022  ...       05/13/2022  \
Payton Pritchard           18.5         0.0        26.0  ...              3.5   
Robert Williams III        17.5       18.75       27.25  ...              NaN   
Sam Hauser                  NaN         NaN         NaN  ...              NaN   
0                    Miami Heat  Miami Heat  Miami Heat  ...  Milwaukee Bucks   
Efficiency                1.052       1.052       1.052  ...            1.075   

                     05/17/2022       05/03/2022  05/29/2022       05/15/2022  \
Payton Pritchard          33.75            14.75         0.0            26.75   
Robert Williams III       34.25             20.0        6.75              NaN   
Sam Hauser                  NaN             3.25         NaN              NaN   
0                    Miami Heat  Milwaukee Bucks  Miami Heat  Milwaukee Bucks   
Efficiency                1.052            1.075       1.052            1.075   

                          05/01/2022             06/08/2022     04/25/2022  \
Payton Pritchard                 9.5                    4.5           4.25   
Robert Williams III             24.0                   34.5          10.75   
Sam Hauser                       0.0                    0.0            NaN   
0                    Milwaukee Bucks  Golden State Warriors  Brooklyn Nets   
Efficiency                     1.075                  1.042          1.093   

                        04/20/2022     04/23/2022  
Payton Pritchard              16.0           14.5  
Robert Williams III            NaN            8.0  
Sam Hauser                     NaN            NaN  
0                    Brooklyn Nets  Brooklyn Nets  
Efficiency                   1.093          1.093  

[5 rows x 24 columns]

In [65]:
tester_eff = pd.DataFrame.transpose(data_efficiency_df)
tester_eff.drop(columns=[0], inplace=True)
tester_eff.head()

Aaron Nesmith Al Horford Daniel Theis Derrick White Grant Williams  \
06/16/2022           0.0       46.0          NaN          5.75           7.25   
06/02/2022           0.0       42.0          5.5         28.25           8.25   
06/10/2022           NaN       24.0          NaN         20.75           4.75   
06/05/2022          11.5       14.5         9.25          25.5          11.25   
06/13/2022          4.25      21.75          NaN          8.75          11.25   

           Jaylen Brown Jayson Tatum Juwan Morgan Luke Kornet Malik Fitts  \
06/16/2022        49.25        33.25          0.0        0.75         NaN   
06/02/2022        45.25        39.25          0.0         NaN         0.0   
06/10/2022         33.5        52.75          NaN         NaN         NaN   
06/05/2022         29.5         43.0          NaN         3.5         3.5   
06/13/2022        34.75         46.0         1.25        4.75         NaN   

           Marcus Smart Nik Stauskas Payton Pritchard Robert Williams III  \
06/16/2022         33.0          0.0             2.25               30.75   
06/02/2022        36.25          0.0             19.5                24.5   
06/10/2022         39.0          NaN             1.75                34.0   
06/05/2022         11.5         8.75             13.5                10.0   
06/13/2022        26.25          0.0             0.75                23.0   

           Sam Hauser Efficiency  
06/16/2022        0.0      1.042  
06/02/2022        0.0      1.042  
06/10/2022        NaN      1.042  
06/05/2022        5.0      1.042  
06/13/2022        1.5      1.042

In [90]:
tester_eff["Aaron Nesmith"].dropna()

06/16/2022      0.0
06/02/2022      0.0
06/05/2022     11.5
06/13/2022     4.25
05/25/2022      0.0
05/19/2022     1.25
05/27/2022      0.0
05/23/2022    10.25
05/21/2022      0.0
05/13/2022     1.25
05/17/2022     8.75
05/03/2022     1.25
05/15/2022     4.75
05/01/2022     2.75
06/08/2022     1.25
Name: Aaron Nesmith, dtype: object

In [97]:
hstack((rent_rate, eff, predict)) 

array([[0.0, 1.042, 0.0],
       [0.0, 1.042, 0.0],
       [11.5, 1.042, 11.5],
       [4.25, 1.042, 4.25],
       [0.0, 1.052, 0.0],
       [1.25, 1.052, 1.25],
       [0.0, 1.052, 0.0],
       [10.25, 1.052, 10.25],
       [0.0, 1.052, 0.0],
       [1.25, 1.075, 1.25],
       [8.75, 1.052, 8.75],
       [1.25, 1.075, 1.25],
       [4.75, 1.075, 4.75],
       [2.75, 1.075, 2.75],
       [1.25, 1.042, 1.25]], dtype=object)

In [93]:
eff

[1.042,
 1.042,
 1.042,
 1.042,
 1.052,
 1.052,
 1.052,
 1.052,
 1.052,
 1.075,
 1.052,
 1.075,
 1.075,
 1.075,
 1.042]

In [179]:
add = {}

#iterate through index
for column in columns:
    print(column)
    
# univariate data prep LSTM
    from numpy import array

    # split sequence
    def split_sequence(sequence, n_steps):
        X, y = list(), list()
        for i in range(len(sequence)):
            # find end of pattern 
            end_ix = i + n_steps
            #check if beyond sequence to break
            if end_ix > len(sequence):
                break
            #gather input and output parts of the pattern
            seq_x, seq_y = sequence[i:end_ix, :-1], sequence[end_ix-1, -1]
            X.append(seq_x)
            y.append(seq_y)
        return array(X), array(y)
    # sequence 
    df = tester_eff[[column, "Efficiency"]].dropna()
    
    name = df.columns[0]
    
    rent_rate = array(df[name])
    
    eff = array(df["Efficiency"])
    
    predict = rent_rate
    
    
    # convert to [rows, columns] structure
    rent_rate = rent_rate.reshape((len(rent_rate), 1))
    eff = eff.reshape((len(eff), 1))
    predict = predict.reshape((len(predict), 1))
    
    # number of steps
    n_steps = 3
    if len(rent_rate) < 5:
        continue   
        
    # horizontally stack columns
    dataset = hstack((rent_rate, eff, predict))    
        
    X, y = split_sequence(dataset, n_steps)
    
    X = X.astype(float)
    # summarize the data
    for i in range(len(X)):
        print(X[i], y[i])

    # reshape from [samples, timesteps] into [samples, timesteps, features]
    n_features = X.shape[2]

    model = Sequential()
    model.add(LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
    model.add(Dense(1))
    model.compile(optimizer='adam', loss='mse')

    # fit model
    model.fit(X, y, epochs=200, verbose=0)
    
    rent = []
    pred = []
    for i in rent_rate[-3:]:
        rent.append(i[0])
        pred.append(i[0])
    eff_pred = []
    for i in eff[-3:]:
        eff_pred.append(i[0])

    # demonstrate prediction
    x_input = array([[rent[0], eff_pred[0]], [rent[1], eff_pred[1]], [rent[2], eff_pred[2]]])
    x_input = x_input.reshape((1, n_steps, n_features))
    yhat = model.predict(x_input, verbose=0)
    add[column] = yhat.tolist()[0][0]

Aaron Nesmith
[[ 0.     1.042]
 [ 0.     1.042]
 [11.5    1.042]] 11.5
[[ 0.     1.042]
 [11.5    1.042]
 [ 4.25   1.042]] 4.25
[[11.5    1.042]
 [ 4.25   1.042]
 [ 0.     1.052]] 0.0
[[4.25  1.042]
 [0.    1.052]
 [1.25  1.052]] 1.25
[[0.    1.052]
 [1.25  1.052]
 [0.    1.052]] 0.0
[[ 1.25   1.052]
 [ 0.     1.052]
 [10.25   1.052]] 10.25
[[ 0.     1.052]
 [10.25   1.052]
 [ 0.     1.052]] 0.0
[[10.25   1.052]
 [ 0.     1.052]
 [ 1.25   1.075]] 1.25
[[0.    1.052]
 [1.25  1.075]
 [8.75  1.052]] 8.75
[[1.25  1.075]
 [8.75  1.052]
 [1.25  1.075]] 1.25
[[8.75  1.052]
 [1.25  1.075]
 [4.75  1.075]] 4.75
[[1.25  1.075]
 [4.75  1.075]
 [2.75  1.075]] 2.75
[[4.75  1.075]
 [2.75  1.075]
 [1.25  1.042]] 1.25


2022-09-10 21:42:47.543408: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Al Horford
[[46.     1.042]
 [42.     1.042]
 [24.     1.042]] 24.0
[[42.     1.042]
 [24.     1.042]
 [14.5    1.042]] 14.5
[[24.     1.042]
 [14.5    1.042]
 [21.75   1.042]] 21.75
[[14.5    1.042]
 [21.75   1.042]
 [44.25   1.093]] 44.25
[[21.75   1.042]
 [44.25   1.093]
 [38.25   1.052]] 38.25
[[44.25   1.093]
 [38.25   1.052]
 [21.75   1.052]] 21.75
[[38.25   1.052]
 [21.75   1.052]
 [20.75   1.052]] 20.75
[[21.75   1.052]
 [20.75   1.052]
 [34.25   1.052]] 34.25
[[20.75   1.052]
 [34.25   1.052]
 [48.     1.052]] 48.0
[[34.25   1.052]
 [48.     1.052]
 [48.5    1.075]] 48.5
[[48.     1.052]
 [48.5    1.075]
 [34.5    1.075]] 34.5
[[48.5    1.075]
 [34.5    1.075]
 [55.5    1.075]] 55.5
[[34.5    1.075]
 [55.5    1.075]
 [28.5    1.075]] 28.5
[[55.5    1.075]
 [28.5    1.075]
 [39.25   1.075]] 39.25
[[28.5    1.075]
 [39.25   1.075]
 [33.5    1.052]] 33.5
[[39.25   1.075]
 [33.5    1.052]
 [29.5    1.075]] 29.5
[[33.5    1.052]
 [29.5    1.075]
 [36.     1.075]] 36.0
[[29.5    1.0

2022-09-10 21:42:50.945458: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 21:42:51.370256: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Daniel Theis
[[ 5.5    1.042]
 [ 9.25   1.042]
 [13.     1.093]] 13.0
[[ 9.25   1.042]
 [13.     1.093]
 [ 4.75   1.052]] 4.75
[[13.     1.093]
 [ 4.75   1.052]
 [ 7.75   1.052]] 7.75
[[4.75  1.052]
 [7.75  1.052]
 [5.25  1.052]] 5.25
[[7.75  1.052]
 [5.25  1.052]
 [2.25  1.075]] 2.25
[[ 5.25   1.052]
 [ 2.25   1.075]
 [14.75   1.075]] 14.75
[[ 2.25   1.075]
 [14.75   1.075]
 [ 0.75   1.075]] 0.75
[[14.75   1.075]
 [ 0.75   1.075]
 [ 6.5    1.075]] 6.5
[[ 0.75   1.075]
 [ 6.5    1.075]
 [18.     1.052]] 18.0
[[ 6.5    1.075]
 [18.     1.052]
 [ 9.75   1.075]] 9.75
[[18.     1.052]
 [ 9.75   1.075]
 [ 6.     1.075]] 6.0
[[ 9.75   1.075]
 [ 6.     1.075]
 [20.5    1.093]] 20.5
[[ 6.     1.075]
 [20.5    1.093]
 [26.5    1.093]] 26.5
[[20.5    1.093]
 [26.5    1.093]
 [20.     1.093]] 20.0


2022-09-10 21:42:54.903701: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 21:42:55.339240: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Derrick White
[[ 5.75   1.042]
 [28.25   1.042]
 [20.75   1.042]] 20.75
[[28.25   1.042]
 [20.75   1.042]
 [25.5    1.042]] 25.5
[[20.75   1.042]
 [25.5    1.042]
 [ 8.75   1.042]] 8.75
[[25.5    1.042]
 [ 8.75   1.042]
 [22.25   1.093]] 22.25
[[ 8.75   1.042]
 [22.25   1.093]
 [27.25   1.052]] 27.25
[[22.25   1.093]
 [27.25   1.052]
 [43.25   1.052]] 43.25
[[27.25   1.052]
 [43.25   1.052]
 [39.     1.052]] 39.0
[[43.25   1.052]
 [39.     1.052]
 [ 8.     1.052]] 8.0
[[39.     1.052]
 [ 8.     1.052]
 [23.     1.075]] 23.0
[[ 8.     1.052]
 [23.     1.075]
 [28.25   1.075]] 28.25
[[23.     1.075]
 [28.25   1.075]
 [19.5    1.075]] 19.5
[[28.25   1.075]
 [19.5    1.075]
 [22.75   1.075]] 22.75
[[19.5    1.075]
 [22.75   1.075]
 [10.     1.052]] 10.0
[[22.75   1.075]
 [10.     1.052]
 [13.5    1.075]] 13.5
[[10.     1.052]
 [13.5    1.075]
 [14.75   1.052]] 14.75
[[13.5    1.075]
 [14.75   1.052]
 [ 9.5    1.075]] 9.5
[[14.75   1.052]
 [ 9.5    1.075]
 [16.5    1.075]] 16.5
[[ 9.5    1.

2022-09-10 21:42:58.863279: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 21:42:59.298813: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Grant Williams
[[7.25  1.042]
 [8.25  1.042]
 [4.75  1.042]] 4.75
[[ 8.25   1.042]
 [ 4.75   1.042]
 [11.25   1.042]] 11.25
[[ 4.75   1.042]
 [11.25   1.042]
 [11.25   1.042]] 11.25
[[11.25   1.042]
 [11.25   1.042]
 [13.     1.093]] 13.0
[[11.25   1.042]
 [13.     1.093]
 [12.5    1.052]] 12.5
[[13.     1.093]
 [12.5    1.052]
 [27.     1.052]] 27.0
[[12.5    1.052]
 [27.     1.052]
 [ 6.5    1.052]] 6.5
[[27.     1.052]
 [ 6.5    1.052]
 [16.25   1.052]] 16.25
[[ 6.5    1.052]
 [16.25   1.052]
 [20.75   1.052]] 20.75
[[16.25   1.052]
 [20.75   1.052]
 [13.5    1.075]] 13.5
[[20.75   1.052]
 [13.5    1.075]
 [ 3.     1.075]] 3.0
[[13.5    1.075]
 [ 3.     1.075]
 [25.5    1.075]] 25.5
[[ 3.     1.075]
 [25.5    1.075]
 [13.25   1.075]] 13.25
[[25.5    1.075]
 [13.25   1.075]
 [12.75   1.052]] 12.75
[[13.25   1.075]
 [12.75   1.052]
 [33.25   1.075]] 33.25
[[12.75   1.052]
 [33.25   1.075]
 [19.5    1.052]] 19.5
[[33.25   1.075]
 [19.5    1.052]
 [41.5    1.075]] 41.5
[[19.5    1.052]


2022-09-10 21:43:02.711567: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 21:43:03.141267: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Jaylen Brown
[[49.25   1.042]
 [45.25   1.042]
 [33.5    1.042]] 33.5
[[45.25   1.042]
 [33.5    1.042]
 [29.5    1.042]] 29.5
[[33.5    1.042]
 [29.5    1.042]
 [34.75   1.042]] 34.75
[[29.5    1.042]
 [34.75   1.042]
 [45.25   1.093]] 45.25
[[34.75   1.042]
 [45.25   1.093]
 [36.     1.052]] 36.0
[[45.25   1.093]
 [36.     1.052]
 [40.     1.052]] 40.0
[[36.     1.052]
 [40.     1.052]
 [37.5    1.052]] 37.5
[[40.     1.052]
 [37.5    1.052]
 [23.75   1.052]] 23.75
[[37.5    1.052]
 [23.75   1.052]
 [54.75   1.052]] 54.75
[[23.75   1.052]
 [54.75   1.052]
 [25.25   1.075]] 25.25
[[54.75   1.052]
 [25.25   1.075]
 [47.5    1.075]] 47.5
[[25.25   1.075]
 [47.5    1.075]
 [48.5    1.075]] 48.5
[[47.5    1.075]
 [48.5    1.075]
 [37.25   1.075]] 37.25
[[48.5    1.075]
 [37.25   1.075]
 [44.     1.052]] 44.0
[[37.25   1.075]
 [44.     1.052]
 [54.5    1.075]] 54.5
[[44.     1.052]
 [54.5    1.075]
 [39.     1.052]] 39.0
[[54.5    1.075]
 [39.     1.052]
 [33.     1.075]] 33.0
[[39.     1.

2022-09-10 21:43:06.471885: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 21:43:07.268861: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Jayson Tatum
[[33.25   1.042]
 [39.25   1.042]
 [52.75   1.042]] 52.75
[[39.25   1.042]
 [52.75   1.042]
 [43.     1.042]] 43.0
[[52.75   1.042]
 [43.     1.042]
 [46.     1.042]] 46.0
[[43.     1.042]
 [46.     1.042]
 [53.     1.093]] 53.0
[[46.     1.042]
 [53.     1.093]
 [49.     1.052]] 49.0
[[53.     1.093]
 [49.     1.052]
 [43.25   1.052]] 43.25
[[49.     1.052]
 [43.25   1.052]
 [51.75   1.052]] 51.75
[[43.25   1.052]
 [51.75   1.052]
 [51.5    1.052]] 51.5
[[51.75   1.052]
 [51.5    1.052]
 [21.     1.052]] 21.0
[[51.5    1.052]
 [21.     1.052]
 [54.25   1.075]] 54.25
[[21.     1.052]
 [54.25   1.075]
 [52.     1.075]] 52.0
[[54.25   1.075]
 [52.     1.075]
 [24.25   1.075]] 24.25
[[52.     1.075]
 [24.25   1.075]
 [66.75   1.075]] 66.75
[[24.25   1.075]
 [66.75   1.075]
 [55.5    1.052]] 55.5
[[66.75   1.075]
 [55.5    1.052]
 [53.25   1.075]] 53.25
[[55.5    1.052]
 [53.25   1.075]
 [54.5    1.052]] 54.5
[[53.25   1.075]
 [54.5    1.052]
 [43.5    1.075]] 43.5
[[54.5    1

2022-09-10 21:43:10.631183: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 21:43:11.046936: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Juwan Morgan
[[0.    1.042]
 [0.    1.042]
 [1.25  1.042]] 1.25
[[0.    1.042]
 [1.25  1.042]
 [0.    1.052]] 0.0
[[1.25  1.042]
 [0.    1.052]
 [2.25  1.052]] 2.25
[[0.    1.052]
 [2.25  1.052]
 [0.    1.052]] 0.0
[[2.25  1.052]
 [0.    1.052]
 [1.25  1.052]] 1.25
[[0.    1.052]
 [1.25  1.052]
 [0.    1.075]] 0.0
[[1.25  1.052]
 [0.    1.075]
 [0.    1.042]] 0.0


2022-09-10 21:43:14.392428: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 21:43:14.801588: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Luke Kornet
[[0.75  1.042]
 [3.5   1.042]
 [4.75  1.042]] 4.75
[[3.5   1.042]
 [4.75  1.042]
 [0.    1.052]] 0.0
[[4.75  1.042]
 [0.    1.052]
 [4.5   1.052]] 4.5
[[0.    1.052]
 [4.5   1.052]
 [0.    1.052]] 0.0
[[4.5   1.052]
 [0.    1.052]
 [1.25  1.075]] 1.25
[[0.    1.052]
 [1.25  1.075]
 [0.    1.075]] 0.0
[[1.25  1.075]
 [0.    1.075]
 [0.    1.075]] 0.0


2022-09-10 21:43:18.117627: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 21:43:18.538391: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Malik Fitts
[[0.    1.042]
 [3.5   1.042]
 [0.    1.052]] 0.0
[[3.5   1.042]
 [0.    1.052]
 [0.    1.052]] 0.0
[[0.    1.052]
 [0.    1.052]
 [0.    1.052]] 0.0
[[0.    1.052]
 [0.    1.052]
 [1.25  1.075]] 1.25
[[0.    1.052]
 [1.25  1.075]
 [3.5   1.075]] 3.5
[[1.25  1.075]
 [3.5   1.075]
 [3.25  1.075]] 3.25
[[3.5   1.075]
 [3.25  1.075]
 [0.    1.042]] 0.0


2022-09-10 21:43:21.839568: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 21:43:22.602733: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Marcus Smart
[[33.     1.042]
 [36.25   1.042]
 [39.     1.042]] 39.0
[[36.25   1.042]
 [39.     1.042]
 [11.5    1.042]] 11.5
[[39.     1.042]
 [11.5    1.042]
 [26.25   1.042]] 26.25
[[11.5    1.042]
 [26.25   1.042]
 [42.25   1.093]] 42.25
[[26.25   1.042]
 [42.25   1.093]
 [17.25   1.052]] 17.25
[[42.25   1.093]
 [17.25   1.052]
 [63.25   1.052]] 63.25
[[17.25   1.052]
 [63.25   1.052]
 [25.     1.052]] 25.0
[[63.25   1.052]
 [25.     1.052]
 [30.     1.052]] 30.0
[[25.     1.052]
 [30.     1.052]
 [36.     1.075]] 36.0
[[30.     1.052]
 [36.     1.075]
 [27.5    1.075]] 27.5
[[36.     1.075]
 [27.5    1.075]
 [15.5    1.075]] 15.5
[[27.5    1.075]
 [15.5    1.075]
 [40.25   1.075]] 40.25
[[15.5    1.075]
 [40.25   1.075]
 [47.75   1.052]] 47.75
[[40.25   1.075]
 [47.75   1.052]
 [38.25   1.075]] 38.25
[[47.75   1.052]
 [38.25   1.075]
 [23.25   1.075]] 23.25
[[38.25   1.075]
 [23.25   1.075]
 [39.25   1.042]] 39.25
[[23.25   1.075]
 [39.25   1.042]
 [43.75   1.093]] 43.75
[[39.25 

2022-09-10 21:43:25.898532: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 21:43:26.308577: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Nik Stauskas
[[0.    1.042]
 [0.    1.042]
 [8.75  1.042]] 8.75
[[0.    1.042]
 [8.75  1.042]
 [0.    1.042]] 0.0
[[8.75  1.042]
 [0.    1.042]
 [0.    1.052]] 0.0
[[0.    1.042]
 [0.    1.052]
 [7.75  1.052]] 7.75
[[0.    1.052]
 [7.75  1.052]
 [2.    1.052]] 2.0
[[7.75  1.052]
 [2.    1.052]
 [3.5   1.052]] 3.5
[[2.    1.052]
 [3.5   1.052]
 [2.    1.075]] 2.0
[[3.5   1.052]
 [2.    1.075]
 [0.    1.075]] 0.0
[[2.    1.075]
 [0.    1.075]
 [1.5   1.075]] 1.5
[[0.    1.075]
 [1.5   1.075]
 [0.    1.075]] 0.0
[[1.5   1.075]
 [0.    1.075]
 [0.    1.042]] 0.0


2022-09-10 21:43:29.657075: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 21:43:30.073591: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Payton Pritchard
[[ 2.25   1.042]
 [19.5    1.042]
 [ 1.75   1.042]] 1.75
[[19.5    1.042]
 [ 1.75   1.042]
 [13.5    1.042]] 13.5
[[ 1.75   1.042]
 [13.5    1.042]
 [ 0.75   1.042]] 0.75
[[13.5    1.042]
 [ 0.75   1.042]
 [ 4.75   1.093]] 4.75
[[0.75  1.042]
 [4.75  1.093]
 [1.25  1.052]] 1.25
[[ 4.75   1.093]
 [ 1.25   1.052]
 [18.5    1.052]] 18.5
[[ 1.25   1.052]
 [18.5    1.052]
 [ 0.     1.052]] 0.0
[[18.5    1.052]
 [ 0.     1.052]
 [26.     1.052]] 26.0
[[ 0.     1.052]
 [26.     1.052]
 [ 9.5    1.052]] 9.5
[[26.     1.052]
 [ 9.5    1.052]
 [11.75   1.075]] 11.75
[[ 9.5    1.052]
 [11.75   1.075]
 [ 8.     1.075]] 8.0
[[11.75   1.075]
 [ 8.     1.075]
 [ 7.     1.075]] 7.0
[[8.    1.075]
 [7.    1.075]
 [3.5   1.075]] 3.5
[[ 7.     1.075]
 [ 3.5    1.075]
 [33.75   1.052]] 33.75
[[ 3.5    1.075]
 [33.75   1.052]
 [14.75   1.075]] 14.75
[[33.75   1.052]
 [14.75   1.075]
 [ 0.     1.052]] 0.0
[[14.75   1.075]
 [ 0.     1.052]
 [26.75   1.075]] 26.75
[[ 0.     1.052]
 [26.75   1

2022-09-10 21:43:33.413603: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 21:43:33.823156: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Robert Williams III
[[30.75   1.042]
 [24.5    1.042]
 [34.     1.042]] 34.0
[[24.5    1.042]
 [34.     1.042]
 [10.     1.042]] 10.0
[[34.     1.042]
 [10.     1.042]
 [23.     1.042]] 23.0
[[10.     1.042]
 [23.     1.042]
 [26.5    1.052]] 26.5
[[23.     1.042]
 [26.5    1.052]
 [17.5    1.052]] 17.5
[[26.5    1.052]
 [17.5    1.052]
 [18.75   1.052]] 18.75
[[17.5    1.052]
 [18.75   1.052]
 [27.25   1.052]] 27.25
[[18.75   1.052]
 [27.25   1.052]
 [32.25   1.075]] 32.25
[[27.25   1.052]
 [32.25   1.075]
 [34.25   1.052]] 34.25
[[32.25   1.075]
 [34.25   1.052]
 [20.     1.075]] 20.0
[[34.25   1.052]
 [20.     1.075]
 [ 6.75   1.052]] 6.75
[[20.     1.075]
 [ 6.75   1.052]
 [24.     1.075]] 24.0
[[ 6.75   1.052]
 [24.     1.075]
 [34.5    1.042]] 34.5
[[24.     1.075]
 [34.5    1.042]
 [10.75   1.093]] 10.75
[[34.5    1.042]
 [10.75   1.093]
 [ 8.     1.093]] 8.0


2022-09-10 21:43:37.176371: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 21:43:37.589218: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Sam Hauser
[[0.    1.042]
 [0.    1.042]
 [5.    1.042]] 5.0
[[0.    1.042]
 [5.    1.042]
 [1.5   1.042]] 1.5
[[5.    1.042]
 [1.5   1.042]
 [3.25  1.075]] 3.25
[[1.5   1.042]
 [3.25  1.075]
 [0.    1.075]] 0.0
[[3.25  1.075]
 [0.    1.075]
 [0.    1.042]] 0.0


2022-09-10 21:43:41.018920: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 21:43:41.829910: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 21:43:45.211773: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


In [180]:
add

{'Aaron Nesmith': 1.1010284423828125,
 'Al Horford': 15.41996955871582,
 'Daniel Theis': 20.017879486083984,
 'Derrick White': 12.299777030944824,
 'Grant Williams': 16.760189056396484,
 'Jaylen Brown': 38.3687858581543,
 'Jayson Tatum': 65.13274383544922,
 'Juwan Morgan': -0.02259661629796028,
 'Luke Kornet': -0.05909275263547897,
 'Malik Fitts': 0.002770889550447464,
 'Marcus Smart': 30.925310134887695,
 'Nik Stauskas': 0.03696215897798538,
 'Payton Pritchard': 14.317920684814453,
 'Robert Williams III': 8.039493560791016,
 'Sam Hauser': -0.002224911004304886}

# Stacked LSTM

In [184]:
add = {}

from keras.layers import Bidirectional

#iterate through index
for column in columns:
    print(column)
    
# univariate data prep LSTM
    from numpy import array

    # split sequence
    def split_sequence(sequence, n_steps):
        X, y = list(), list()
        for i in range(len(sequence)):
            # find end of pattern 
            end_ix = i + n_steps
            #check if beyond sequence to break
            if end_ix > len(sequence)-1:
                break
            #gather input and output parts of the pattern
            seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
            X.append(seq_x)
            y.append(seq_y)
        return array(X), array(y)
    # sequence 
    rent_rate = list(tester[column].dropna())
    # number of steps
    n_steps = 3
    if len(rent_rate) < 5:
        continue
    X, y = split_sequence(rent_rate, n_steps)
    # summarize the data
    for i in range(len(X)):
        print(X[i], y[i])

    # reshape from [samples, timesteps] into [samples, timesteps, features]
    n_features = 1
    X = X.reshape((X.shape[0], X.shape[1], n_features))

    model = Sequential()
    model.add(Bidirectional(LSTM(50, activation='relu', input_shape=(n_steps, n_features))))
    model.add(Dense(1))
    model.compile(optimizer='adam', loss='mse')

    # fit model
    model.fit(X, y, epochs=200, verbose=0)

    # demonstrate prediction
    x_input = array(rent_rate[-3:])
    x_input = x_input.reshape((1, n_steps, n_features))
    yhat = model.predict(x_input, verbose=0)
    add[column] = yhat.tolist()[0][0]

Aaron Nesmith
[ 0.   0.  11.5] 4.25
[ 0.   11.5   4.25] 0.0
[11.5   4.25  0.  ] 1.25
[4.25 0.   1.25] 0.0
[0.   1.25 0.  ] 10.25
[ 1.25  0.   10.25] 0.0
[ 0.   10.25  0.  ] 1.25
[10.25  0.    1.25] 8.75
[0.   1.25 8.75] 1.25
[1.25 8.75 1.25] 4.75
[8.75 1.25 4.75] 2.75
[1.25 4.75 2.75] 1.25


2022-09-10 21:50:05.144096: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Al Horford
[46. 42. 24.] 14.5
[42.  24.  14.5] 21.75
[24.   14.5  21.75] 44.25
[14.5  21.75 44.25] 38.25
[21.75 44.25 38.25] 21.75
[44.25 38.25 21.75] 20.75
[38.25 21.75 20.75] 34.25
[21.75 20.75 34.25] 48.0
[20.75 34.25 48.  ] 48.5
[34.25 48.   48.5 ] 34.5
[48.  48.5 34.5] 55.5
[48.5 34.5 55.5] 28.5
[34.5 55.5 28.5] 39.25
[55.5  28.5  39.25] 33.5
[28.5  39.25 33.5 ] 29.5
[39.25 33.5  29.5 ] 36.0
[33.5 29.5 36. ] 34.5
[29.5 36.  34.5] 23.0
[36.  34.5 23. ] 34.0
[34.5 23.  34. ] 15.25


2022-09-10 21:50:10.990302: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 21:50:11.738921: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Daniel Theis
[ 5.5   9.25 13.  ] 4.75
[ 9.25 13.    4.75] 7.75
[13.    4.75  7.75] 5.25
[4.75 7.75 5.25] 2.25
[7.75 5.25 2.25] 14.75
[ 5.25  2.25 14.75] 0.75
[ 2.25 14.75  0.75] 6.5
[14.75  0.75  6.5 ] 18.0
[ 0.75  6.5  18.  ] 9.75
[ 6.5  18.    9.75] 6.0
[18.    9.75  6.  ] 20.5
[ 9.75  6.   20.5 ] 26.5
[ 6.  20.5 26.5] 20.0


2022-09-10 21:50:17.687902: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 21:50:18.879726: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Derrick White
[ 5.75 28.25 20.75] 25.5
[28.25 20.75 25.5 ] 8.75
[20.75 25.5   8.75] 22.25
[25.5   8.75 22.25] 27.25
[ 8.75 22.25 27.25] 43.25
[22.25 27.25 43.25] 39.0
[27.25 43.25 39.  ] 8.0
[43.25 39.    8.  ] 23.0
[39.  8. 23.] 28.25
[ 8.   23.   28.25] 19.5
[23.   28.25 19.5 ] 22.75
[28.25 19.5  22.75] 10.0
[19.5  22.75 10.  ] 13.5
[22.75 10.   13.5 ] 14.75
[10.   13.5  14.75] 9.5
[13.5  14.75  9.5 ] 16.5
[14.75  9.5  16.5 ] 14.75
[ 9.5  16.5  14.75] 19.5
[16.5  14.75 19.5 ] 8.25
[14.75 19.5   8.25] 12.5


2022-09-10 21:50:24.586264: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 21:50:25.307156: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Grant Williams
[7.25 8.25 4.75] 11.25
[ 8.25  4.75 11.25] 11.25
[ 4.75 11.25 11.25] 13.0
[11.25 11.25 13.  ] 12.5
[11.25 13.   12.5 ] 27.0
[13.  12.5 27. ] 6.5
[12.5 27.   6.5] 16.25
[27.    6.5  16.25] 20.75
[ 6.5  16.25 20.75] 13.5
[16.25 20.75 13.5 ] 3.0
[20.75 13.5   3.  ] 25.5
[13.5  3.  25.5] 13.25
[ 3.   25.5  13.25] 12.75
[25.5  13.25 12.75] 33.25
[13.25 12.75 33.25] 19.5
[12.75 33.25 19.5 ] 41.5
[33.25 19.5  41.5 ] 16.0
[19.5 41.5 16. ] 18.25
[41.5  16.   18.25] 26.75
[16.   18.25 26.75] 30.0
[18.25 26.75 30.  ] 16.75


2022-09-10 21:50:31.028266: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 21:50:32.078633: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Jaylen Brown
[49.25 45.25 33.5 ] 29.5
[45.25 33.5  29.5 ] 34.75
[33.5  29.5  34.75] 45.25
[29.5  34.75 45.25] 36.0
[34.75 45.25 36.  ] 40.0
[45.25 36.   40.  ] 37.5
[36.  40.  37.5] 23.75
[40.   37.5  23.75] 54.75
[37.5  23.75 54.75] 25.25
[23.75 54.75 25.25] 47.5
[54.75 25.25 47.5 ] 48.5
[25.25 47.5  48.5 ] 37.25
[47.5  48.5  37.25] 44.0
[48.5  37.25 44.  ] 54.5
[37.25 44.   54.5 ] 39.0
[44.  54.5 39. ] 33.0
[54.5 39.  33. ] 31.25
[39.   33.   31.25] 48.75
[33.   31.25 48.75] 38.0
[31.25 48.75 38.  ] 41.0
[48.75 38.   41.  ] 38.5


2022-09-10 21:50:37.796139: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 21:50:38.520936: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Jayson Tatum
[33.25 39.25 52.75] 43.0
[39.25 52.75 43.  ] 46.0
[52.75 43.   46.  ] 53.0
[43. 46. 53.] 49.0
[46. 53. 49.] 43.25
[53.   49.   43.25] 51.75
[49.   43.25 51.75] 51.5
[43.25 51.75 51.5 ] 21.0
[51.75 51.5  21.  ] 54.25
[51.5  21.   54.25] 52.0
[21.   54.25 52.  ] 24.25
[54.25 52.   24.25] 66.75
[52.   24.25 66.75] 55.5
[24.25 66.75 55.5 ] 53.25
[66.75 55.5  53.25] 54.5
[55.5  53.25 54.5 ] 43.5
[53.25 54.5  43.5 ] 42.0
[54.5 43.5 42. ] 49.5
[43.5 42.  49.5] 39.25
[42.   49.5  39.25] 43.0
[49.5  39.25 43.  ] 65.25


2022-09-10 21:50:44.205229: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 21:50:44.962575: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Juwan Morgan
[0.   0.   1.25] 0.0
[0.   1.25 0.  ] 2.25
[1.25 0.   2.25] 0.0
[0.   2.25 0.  ] 1.25
[2.25 0.   1.25] 0.0
[0.   1.25 0.  ] 0.0


2022-09-10 21:50:50.697731: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 21:50:51.920894: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Luke Kornet
[0.75 3.5  4.75] 0.0
[3.5  4.75 0.  ] 4.5
[4.75 0.   4.5 ] 0.0
[0.  4.5 0. ] 1.25
[4.5  0.   1.25] 0.0
[0.   1.25 0.  ] 0.0


2022-09-10 21:50:57.727290: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 21:50:58.471812: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Malik Fitts
[0.  3.5 0. ] 0.0
[3.5 0.  0. ] 0.0
[0. 0. 0.] 1.25
[0.   0.   1.25] 3.5
[0.   1.25 3.5 ] 3.25
[1.25 3.5  3.25] 0.0


2022-09-10 21:51:04.196364: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 21:51:04.933611: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Marcus Smart
[33.   36.25 39.  ] 11.5
[36.25 39.   11.5 ] 26.25
[39.   11.5  26.25] 42.25
[11.5  26.25 42.25] 17.25
[26.25 42.25 17.25] 63.25
[42.25 17.25 63.25] 25.0
[17.25 63.25 25.  ] 30.0
[63.25 25.   30.  ] 36.0
[25. 30. 36.] 27.5
[30.  36.  27.5] 15.5
[36.  27.5 15.5] 40.25
[27.5  15.5  40.25] 47.75
[15.5  40.25 47.75] 38.25
[40.25 47.75 38.25] 23.25
[47.75 38.25 23.25] 39.25
[38.25 23.25 39.25] 43.75
[23.25 39.25 43.75] 21.25
[39.25 43.75 21.25] 30.75


2022-09-10 21:51:10.596910: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 21:51:11.770870: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Nik Stauskas
[0.   0.   8.75] 0.0
[0.   8.75 0.  ] 0.0
[8.75 0.   0.  ] 7.75
[0.   0.   7.75] 2.0
[0.   7.75 2.  ] 3.5
[7.75 2.   3.5 ] 2.0
[2.  3.5 2. ] 0.0
[3.5 2.  0. ] 1.5
[2.  0.  1.5] 0.0
[0.  1.5 0. ] 0.0


2022-09-10 21:51:17.507650: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 21:51:18.240326: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Payton Pritchard
[ 2.25 19.5   1.75] 13.5
[19.5   1.75 13.5 ] 0.75
[ 1.75 13.5   0.75] 4.75
[13.5   0.75  4.75] 1.25
[0.75 4.75 1.25] 18.5
[ 4.75  1.25 18.5 ] 0.0
[ 1.25 18.5   0.  ] 26.0
[18.5  0.  26. ] 9.5
[ 0.  26.   9.5] 11.75
[26.    9.5  11.75] 8.0
[ 9.5  11.75  8.  ] 7.0
[11.75  8.    7.  ] 3.5
[8.  7.  3.5] 33.75
[ 7.    3.5  33.75] 14.75
[ 3.5  33.75 14.75] 0.0
[33.75 14.75  0.  ] 26.75
[14.75  0.   26.75] 9.5
[ 0.   26.75  9.5 ] 4.5
[26.75  9.5   4.5 ] 4.25
[9.5  4.5  4.25] 16.0
[ 4.5   4.25 16.  ] 14.5


2022-09-10 21:51:24.511267: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 21:51:25.371835: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Robert Williams III
[30.75 24.5  34.  ] 10.0
[24.5 34.  10. ] 23.0
[34. 10. 23.] 26.5
[10.  23.  26.5] 17.5
[23.  26.5 17.5] 18.75
[26.5  17.5  18.75] 27.25
[17.5  18.75 27.25] 32.25
[18.75 27.25 32.25] 34.25
[27.25 32.25 34.25] 20.0
[32.25 34.25 20.  ] 6.75
[34.25 20.    6.75] 24.0
[20.    6.75 24.  ] 34.5
[ 6.75 24.   34.5 ] 10.75
[24.   34.5  10.75] 8.0


2022-09-10 21:51:31.242898: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 21:51:32.600182: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Sam Hauser
[0. 0. 5.] 1.5
[0.  5.  1.5] 3.25
[5.   1.5  3.25] 0.0
[1.5  3.25 0.  ] 0.0


2022-09-10 21:51:38.859844: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 21:51:39.593023: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 21:51:45.653616: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


In [185]:
add

{'Aaron Nesmith': 1.055436611175537,
 'Al Horford': 36.61973571777344,
 'Daniel Theis': 24.368167877197266,
 'Derrick White': 12.109906196594238,
 'Grant Williams': 18.649215698242188,
 'Jaylen Brown': 35.83340835571289,
 'Jayson Tatum': 42.56106185913086,
 'Juwan Morgan': 0.6438660025596619,
 'Luke Kornet': 0.05781029909849167,
 'Malik Fitts': -0.8756077885627747,
 'Marcus Smart': 50.16193389892578,
 'Nik Stauskas': 0.6155680418014526,
 'Payton Pritchard': 3.6163251399993896,
 'Robert Williams III': 32.50277328491211,
 'Sam Hauser': -0.37518152594566345}

In [187]:
add = {}

#iterate through index
for column in columns:
    print(column)
    
# univariate data prep LSTM
    from numpy import array

    # split sequence
    def split_sequence(sequence, n_steps):
        X, y = list(), list()
        for i in range(len(sequence)):
            # find end of pattern 
            end_ix = i + n_steps
            #check if beyond sequence to break
            if end_ix > len(sequence)-1:
                break
            #gather input and output parts of the pattern
            seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
            X.append(seq_x)
            y.append(seq_y)
        return array(X), array(y)
    # sequence 
    rent_rate = list(tester[column].dropna())
    # number of steps
    n_steps = 3
    if len(rent_rate) < 5:
        continue
    X, y = split_sequence(rent_rate, n_steps)
    # summarize the data
    for i in range(len(X)):
        print(X[i], y[i])

    # reshape from [samples, timesteps] into [samples, timesteps, features]
    n_features = 1
    X = X.reshape((X.shape[0], X.shape[1], n_features))

    model = Sequential()
    model.add(LSTM(50, activation='relu', return_sequences=True,input_shape=(n_steps, n_features)))
    model.add(LSTM(50, activation='relu'))
    model.add(Dense(1))
    model.compile(optimizer='adam', loss='mse')

    # fit model
    model.fit(X, y, epochs=200, verbose=0)

    # demonstrate prediction
    x_input = array(rent_rate[-3:])
    x_input = x_input.reshape((1, n_steps, n_features))
    yhat = model.predict(x_input, verbose=0)
    add[column] = yhat.tolist()[0][0]

Aaron Nesmith
[ 0.   0.  11.5] 4.25
[ 0.   11.5   4.25] 0.0
[11.5   4.25  0.  ] 1.25
[4.25 0.   1.25] 0.0
[0.   1.25 0.  ] 10.25
[ 1.25  0.   10.25] 0.0
[ 0.   10.25  0.  ] 1.25
[10.25  0.    1.25] 8.75
[0.   1.25 8.75] 1.25
[1.25 8.75 1.25] 4.75
[8.75 1.25 4.75] 2.75
[1.25 4.75 2.75] 1.25


2022-09-10 21:54:30.106639: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Al Horford
[46. 42. 24.] 14.5
[42.  24.  14.5] 21.75
[24.   14.5  21.75] 44.25
[14.5  21.75 44.25] 38.25
[21.75 44.25 38.25] 21.75
[44.25 38.25 21.75] 20.75
[38.25 21.75 20.75] 34.25
[21.75 20.75 34.25] 48.0
[20.75 34.25 48.  ] 48.5
[34.25 48.   48.5 ] 34.5
[48.  48.5 34.5] 55.5
[48.5 34.5 55.5] 28.5
[34.5 55.5 28.5] 39.25
[55.5  28.5  39.25] 33.5
[28.5  39.25 33.5 ] 29.5
[39.25 33.5  29.5 ] 36.0
[33.5 29.5 36. ] 34.5
[29.5 36.  34.5] 23.0
[36.  34.5 23. ] 34.0
[34.5 23.  34. ] 15.25


2022-09-10 21:54:36.914503: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 21:54:37.687329: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Daniel Theis
[ 5.5   9.25 13.  ] 4.75
[ 9.25 13.    4.75] 7.75
[13.    4.75  7.75] 5.25
[4.75 7.75 5.25] 2.25
[7.75 5.25 2.25] 14.75
[ 5.25  2.25 14.75] 0.75
[ 2.25 14.75  0.75] 6.5
[14.75  0.75  6.5 ] 18.0
[ 0.75  6.5  18.  ] 9.75
[ 6.5  18.    9.75] 6.0
[18.    9.75  6.  ] 20.5
[ 9.75  6.   20.5 ] 26.5
[ 6.  20.5 26.5] 20.0


2022-09-10 21:54:44.416029: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 21:54:45.578689: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Derrick White
[ 5.75 28.25 20.75] 25.5
[28.25 20.75 25.5 ] 8.75
[20.75 25.5   8.75] 22.25
[25.5   8.75 22.25] 27.25
[ 8.75 22.25 27.25] 43.25
[22.25 27.25 43.25] 39.0
[27.25 43.25 39.  ] 8.0
[43.25 39.    8.  ] 23.0
[39.  8. 23.] 28.25
[ 8.   23.   28.25] 19.5
[23.   28.25 19.5 ] 22.75
[28.25 19.5  22.75] 10.0
[19.5  22.75 10.  ] 13.5
[22.75 10.   13.5 ] 14.75
[10.   13.5  14.75] 9.5
[13.5  14.75  9.5 ] 16.5
[14.75  9.5  16.5 ] 14.75
[ 9.5  16.5  14.75] 19.5
[16.5  14.75 19.5 ] 8.25
[14.75 19.5   8.25] 12.5


2022-09-10 21:54:52.206893: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 21:54:52.966691: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Grant Williams
[7.25 8.25 4.75] 11.25
[ 8.25  4.75 11.25] 11.25
[ 4.75 11.25 11.25] 13.0
[11.25 11.25 13.  ] 12.5
[11.25 13.   12.5 ] 27.0
[13.  12.5 27. ] 6.5
[12.5 27.   6.5] 16.25
[27.    6.5  16.25] 20.75
[ 6.5  16.25 20.75] 13.5
[16.25 20.75 13.5 ] 3.0
[20.75 13.5   3.  ] 25.5
[13.5  3.  25.5] 13.25
[ 3.   25.5  13.25] 12.75
[25.5  13.25 12.75] 33.25
[13.25 12.75 33.25] 19.5
[12.75 33.25 19.5 ] 41.5
[33.25 19.5  41.5 ] 16.0
[19.5 41.5 16. ] 18.25
[41.5  16.   18.25] 26.75
[16.   18.25 26.75] 30.0
[18.25 26.75 30.  ] 16.75


2022-09-10 21:54:59.667499: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 21:55:00.425971: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Jaylen Brown
[49.25 45.25 33.5 ] 29.5
[45.25 33.5  29.5 ] 34.75
[33.5  29.5  34.75] 45.25
[29.5  34.75 45.25] 36.0
[34.75 45.25 36.  ] 40.0
[45.25 36.   40.  ] 37.5
[36.  40.  37.5] 23.75
[40.   37.5  23.75] 54.75
[37.5  23.75 54.75] 25.25
[23.75 54.75 25.25] 47.5
[54.75 25.25 47.5 ] 48.5
[25.25 47.5  48.5 ] 37.25
[47.5  48.5  37.25] 44.0
[48.5  37.25 44.  ] 54.5
[37.25 44.   54.5 ] 39.0
[44.  54.5 39. ] 33.0
[54.5 39.  33. ] 31.25
[39.   33.   31.25] 48.75
[33.   31.25 48.75] 38.0
[31.25 48.75 38.  ] 41.0
[48.75 38.   41.  ] 38.5


2022-09-10 21:55:07.033575: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 21:55:07.786768: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Jayson Tatum
[33.25 39.25 52.75] 43.0
[39.25 52.75 43.  ] 46.0
[52.75 43.   46.  ] 53.0
[43. 46. 53.] 49.0
[46. 53. 49.] 43.25
[53.   49.   43.25] 51.75
[49.   43.25 51.75] 51.5
[43.25 51.75 51.5 ] 21.0
[51.75 51.5  21.  ] 54.25
[51.5  21.   54.25] 52.0
[21.   54.25 52.  ] 24.25
[54.25 52.   24.25] 66.75
[52.   24.25 66.75] 55.5
[24.25 66.75 55.5 ] 53.25
[66.75 55.5  53.25] 54.5
[55.5  53.25 54.5 ] 43.5
[53.25 54.5  43.5 ] 42.0
[54.5 43.5 42. ] 49.5
[43.5 42.  49.5] 39.25
[42.   49.5  39.25] 43.0
[49.5  39.25 43.  ] 65.25


2022-09-10 21:55:14.941705: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 21:55:15.710617: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Juwan Morgan
[0.   0.   1.25] 0.0
[0.   1.25 0.  ] 2.25
[1.25 0.   2.25] 0.0
[0.   2.25 0.  ] 1.25
[2.25 0.   1.25] 0.0
[0.   1.25 0.  ] 0.0


2022-09-10 21:55:22.395415: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 21:55:23.130442: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Luke Kornet
[0.75 3.5  4.75] 0.0
[3.5  4.75 0.  ] 4.5
[4.75 0.   4.5 ] 0.0
[0.  4.5 0. ] 1.25
[4.5  0.   1.25] 0.0
[0.   1.25 0.  ] 0.0


2022-09-10 21:55:29.675378: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 21:55:30.876257: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Malik Fitts
[0.  3.5 0. ] 0.0
[3.5 0.  0. ] 0.0
[0. 0. 0.] 1.25
[0.   0.   1.25] 3.5
[0.   1.25 3.5 ] 3.25
[1.25 3.5  3.25] 0.0


2022-09-10 21:55:37.608771: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 21:55:38.371286: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Marcus Smart
[33.   36.25 39.  ] 11.5
[36.25 39.   11.5 ] 26.25
[39.   11.5  26.25] 42.25
[11.5  26.25 42.25] 17.25
[26.25 42.25 17.25] 63.25
[42.25 17.25 63.25] 25.0
[17.25 63.25 25.  ] 30.0
[63.25 25.   30.  ] 36.0
[25. 30. 36.] 27.5
[30.  36.  27.5] 15.5
[36.  27.5 15.5] 40.25
[27.5  15.5  40.25] 47.75
[15.5  40.25 47.75] 38.25
[40.25 47.75 38.25] 23.25
[47.75 38.25 23.25] 39.25
[38.25 23.25 39.25] 43.75
[23.25 39.25 43.75] 21.25
[39.25 43.75 21.25] 30.75


2022-09-10 21:55:44.956794: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 21:55:45.711023: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Nik Stauskas
[0.   0.   8.75] 0.0
[0.   8.75 0.  ] 0.0
[8.75 0.   0.  ] 7.75
[0.   0.   7.75] 2.0
[0.   7.75 2.  ] 3.5
[7.75 2.   3.5 ] 2.0
[2.  3.5 2. ] 0.0
[3.5 2.  0. ] 1.5
[2.  0.  1.5] 0.0
[0.  1.5 0. ] 0.0


2022-09-10 21:55:52.397874: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 21:55:53.632777: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Payton Pritchard
[ 2.25 19.5   1.75] 13.5
[19.5   1.75 13.5 ] 0.75
[ 1.75 13.5   0.75] 4.75
[13.5   0.75  4.75] 1.25
[0.75 4.75 1.25] 18.5
[ 4.75  1.25 18.5 ] 0.0
[ 1.25 18.5   0.  ] 26.0
[18.5  0.  26. ] 9.5
[ 0.  26.   9.5] 11.75
[26.    9.5  11.75] 8.0
[ 9.5  11.75  8.  ] 7.0
[11.75  8.    7.  ] 3.5
[8.  7.  3.5] 33.75
[ 7.    3.5  33.75] 14.75
[ 3.5  33.75 14.75] 0.0
[33.75 14.75  0.  ] 26.75
[14.75  0.   26.75] 9.5
[ 0.   26.75  9.5 ] 4.5
[26.75  9.5   4.5 ] 4.25
[9.5  4.5  4.25] 16.0
[ 4.5   4.25 16.  ] 14.5


2022-09-10 21:56:00.290761: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 21:56:01.055003: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Robert Williams III
[30.75 24.5  34.  ] 10.0
[24.5 34.  10. ] 23.0
[34. 10. 23.] 26.5
[10.  23.  26.5] 17.5
[23.  26.5 17.5] 18.75
[26.5  17.5  18.75] 27.25
[17.5  18.75 27.25] 32.25
[18.75 27.25 32.25] 34.25
[27.25 32.25 34.25] 20.0
[32.25 34.25 20.  ] 6.75
[34.25 20.    6.75] 24.0
[20.    6.75 24.  ] 34.5
[ 6.75 24.   34.5 ] 10.75
[24.   34.5  10.75] 8.0


2022-09-10 21:56:07.652521: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 21:56:08.395099: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Sam Hauser
[0. 0. 5.] 1.5
[0.  5.  1.5] 3.25
[5.   1.5  3.25] 0.0
[1.5  3.25 0.  ] 0.0


2022-09-10 21:56:14.988222: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 21:56:16.196860: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-09-10 21:56:22.866446: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


In [188]:
add

{'Aaron Nesmith': 0.5422657132148743,
 'Al Horford': 34.58259201049805,
 'Daniel Theis': 11.026326179504395,
 'Derrick White': 14.849235534667969,
 'Grant Williams': 23.20965003967285,
 'Jaylen Brown': 33.97257995605469,
 'Jayson Tatum': 40.47640609741211,
 'Juwan Morgan': 0.7292090058326721,
 'Luke Kornet': 0.027965467423200607,
 'Malik Fitts': 0.1250106394290924,
 'Marcus Smart': 42.73813247680664,
 'Nik Stauskas': 0.5476028323173523,
 'Payton Pritchard': 4.129017353057861,
 'Robert Williams III': 31.193336486816406,
 'Sam Hauser': -0.4584226608276367}